//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hyperar.HattrickUltimate.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Controls {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Controls() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Hyperar.HattrickUltimate.Localization.Controls", typeof(Controls).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age.
        /// </summary>
        public static string ColumnSeniorPlayerAge_HeaderText {
            get {
                return ResourceManager.GetString("ColumnSeniorPlayerAge_HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aggressiveness.
        /// </summary>
        public static string ColumnSeniorPlayerAggressiveness_HeaderText {
            get {
                return ResourceManager.GetString("ColumnSeniorPlayerAggressiveness_HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agreeability.
        /// </summary>
        public static string ColumnSeniorPlayerAgreeability_HeaderText {
            get {
                return ResourceManager.GetString("ColumnSeniorPlayerAgreeability_HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cards.
        /// </summary>
        public static string ColumnSeniorPlayerBookingStatus_HeaderText {
            get {
                return ResourceManager.GetString("ColumnSeniorPlayerBookingStatus_HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Career Goals.
        /// </summary>
        public static string ColumnSeniorPlayerCareerGoals_HeaderText {
            get {
                return ResourceManager.GetString("ColumnSeniorPlayerCareerGoals_HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Career Hattricks.
        /// </summary>
        public static string ColumnSeniorPlayerCareerHattricks_HeaderText {
            get {
                return ResourceManager.GetString("ColumnSeniorPlayerCareerHattricks_HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string ColumnSeniorPlayerCategory_HeaderText {
            get {
                return ResourceManager.GetString("ColumnSeniorPlayerCategory_HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nationality (English).
        /// </summary>
        public static string ColumnSeniorPlayerCountryEnglishName_HeaderText {
            get {
                return ResourceManager.GetString("ColumnSeniorPlayerCountryEnglishName_HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nationality.
        /// </summary>
        public static string ColumnSeniorPlayerCountryName_HeaderText {
            get {
                return ResourceManager.GetString("ColumnSeniorPlayerCountryName_HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defending.
        /// </summary>
        public static string ColumnSeniorPlayerDefending_HeaderText {
            get {
                return ResourceManager.GetString("ColumnSeniorPlayerDefending_HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experience.
        /// </summary>
        public static string ColumnSeniorPlayerExperience_HeaderText {
            get {
                return ResourceManager.GetString("ColumnSeniorPlayerExperience_HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string ColumnSeniorPlayerFirstName_HeaderText {
            get {
                return ResourceManager.GetString("ColumnSeniorPlayerFirstName_HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form.
        /// </summary>
        public static string ColumnSeniorPlayerForm_HeaderText {
            get {
                return ResourceManager.GetString("ColumnSeniorPlayerForm_HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motherclub Bonus.
        /// </summary>
        public static string ColumnSeniorPlayerHasHomegrownBonus_HeaderText {
            get {
                return ResourceManager.GetString("ColumnSeniorPlayerHasHomegrownBonus_HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string ColumnSeniorPlayerHattrickId_HeaderText {
            get {
                return ResourceManager.GetString("ColumnSeniorPlayerHattrickId_HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Honesty.
        /// </summary>
        public static string ColumnSeniorPlayerHonesty_HeaderText {
            get {
                return ResourceManager.GetString("ColumnSeniorPlayerHonesty_HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health.
        /// </summary>
        public static string ColumnSeniorPlayerInjuryStatus_HeaderText {
            get {
                return ResourceManager.GetString("ColumnSeniorPlayerInjuryStatus_HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On Transfermarket.
        /// </summary>
        public static string ColumnSeniorPlayerIsOnTransferMarket_HeaderText {
            get {
                return ResourceManager.GetString("ColumnSeniorPlayerIsOnTransferMarket_HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keeper.
        /// </summary>
        public static string ColumnSeniorPlayerKeeper_HeaderText {
            get {
                return ResourceManager.GetString("ColumnSeniorPlayerKeeper_HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string ColumnSeniorPlayerLastName_HeaderText {
            get {
                return ResourceManager.GetString("ColumnSeniorPlayerLastName_HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leadership.
        /// </summary>
        public static string ColumnSeniorPlayerLeadership_HeaderText {
            get {
                return ResourceManager.GetString("ColumnSeniorPlayerLeadership_HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loyalty.
        /// </summary>
        public static string ColumnSeniorPlayerLoyalty_HeaderText {
            get {
                return ResourceManager.GetString("ColumnSeniorPlayerLoyalty_HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U20 NT Matches.
        /// </summary>
        public static string ColumnSeniorPlayerMatchesOnJuniorNationalTeam_HeaderText {
            get {
                return ResourceManager.GetString("ColumnSeniorPlayerMatchesOnJuniorNationalTeam_HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NT Matches.
        /// </summary>
        public static string ColumnSeniorPlayerMatchesOnSeniorNationalTeam_HeaderText {
            get {
                return ResourceManager.GetString("ColumnSeniorPlayerMatchesOnSeniorNationalTeam_HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nickname.
        /// </summary>
        public static string ColumnSeniorPlayerNickName_HeaderText {
            get {
                return ResourceManager.GetString("ColumnSeniorPlayerNickName_HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passing.
        /// </summary>
        public static string ColumnSeniorPlayerPassing_HeaderText {
            get {
                return ResourceManager.GetString("ColumnSeniorPlayerPassing_HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playmaking.
        /// </summary>
        public static string ColumnSeniorPlayerPlaymaking_HeaderText {
            get {
                return ResourceManager.GetString("ColumnSeniorPlayerPlaymaking_HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plays on NT.
        /// </summary>
        public static string ColumnSeniorPlayerPlaysOnNationalTeam_HeaderText {
            get {
                return ResourceManager.GetString("ColumnSeniorPlayerPlaysOnNationalTeam_HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scoring.
        /// </summary>
        public static string ColumnSeniorPlayerScoring_HeaderText {
            get {
                return ResourceManager.GetString("ColumnSeniorPlayerScoring_HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team ID.
        /// </summary>
        public static string ColumnSeniorPlayerSeniorTeamId_HeaderText {
            get {
                return ResourceManager.GetString("ColumnSeniorPlayerSeniorTeamId_HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Pieces.
        /// </summary>
        public static string ColumnSeniorPlayerSetPieces_HeaderText {
            get {
                return ResourceManager.GetString("ColumnSeniorPlayerSetPieces_HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shirt Number.
        /// </summary>
        public static string ColumnSeniorPlayerShirtNumber_HeaderText {
            get {
                return ResourceManager.GetString("ColumnSeniorPlayerShirtNumber_HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specialty.
        /// </summary>
        public static string ColumnSeniorPlayerSpecialty_HeaderText {
            get {
                return ResourceManager.GetString("ColumnSeniorPlayerSpecialty_HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stamina.
        /// </summary>
        public static string ColumnSeniorPlayerStamina_HeaderText {
            get {
                return ResourceManager.GetString("ColumnSeniorPlayerStamina_HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TSI.
        /// </summary>
        public static string ColumnSeniorPlayerTotalSkillIndex_HeaderText {
            get {
                return ResourceManager.GetString("ColumnSeniorPlayerTotalSkillIndex_HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wage.
        /// </summary>
        public static string ColumnSeniorPlayerWage_HeaderText {
            get {
                return ResourceManager.GetString("ColumnSeniorPlayerWage_HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Winger.
        /// </summary>
        public static string ColumnSeniorPlayerWinger_HeaderText {
            get {
                return ResourceManager.GetString("ColumnSeniorPlayerWinger_HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Junior Players.
        /// </summary>
        public static string DownloadItemCategory_JuniorPlayers {
            get {
                return ResourceManager.GetString("DownloadItemCategory_JuniorPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senior Players.
        /// </summary>
        public static string DownloadItemCategory_SeniorPlayers {
            get {
                return ResourceManager.GetString("DownloadItemCategory_SeniorPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senior Team.
        /// </summary>
        public static string DownloadItemCategory_SeniorTeam {
            get {
                return ResourceManager.GetString("DownloadItemCategory_SeniorTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Includes the players&apos; last match information..
        /// </summary>
        public static string DownloadItemDescription_IncludeJuniorPlayerMatchInfo {
            get {
                return ResourceManager.GetString("DownloadItemDescription_IncludeJuniorPlayerMatchInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Includes the players&apos; last match information..
        /// </summary>
        public static string DownloadItemDescription_IncludeSeniorPlayerMatchInfo {
            get {
                return ResourceManager.GetString("DownloadItemDescription_IncludeSeniorPlayerMatchInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Includes the country flags of the teams that you have visited to play a friendly match..
        /// </summary>
        public static string DownloadItemDescription_IncludeSeniorTeamAwayFlags {
            get {
                return ResourceManager.GetString("DownloadItemDescription_IncludeSeniorTeamAwayFlags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Includes the country flags of the teams that have visited you to play a friendly match..
        /// </summary>
        public static string DownloadItemDescription_IncludeSeniorTeamHomeFlags {
            get {
                return ResourceManager.GetString("DownloadItemDescription_IncludeSeniorTeamHomeFlags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include Player Match Info.
        /// </summary>
        public static string DownloadItemDisplayName_IncludeJuniorPlayerMatchInfo {
            get {
                return ResourceManager.GetString("DownloadItemDisplayName_IncludeJuniorPlayerMatchInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include Player Match Info.
        /// </summary>
        public static string DownloadItemDisplayName_IncludeSeniorPlayerMatchInfo {
            get {
                return ResourceManager.GetString("DownloadItemDisplayName_IncludeSeniorPlayerMatchInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include Away Flags.
        /// </summary>
        public static string DownloadItemDisplayName_IncludeSeniorTeamAwayFlags {
            get {
                return ResourceManager.GetString("DownloadItemDisplayName_IncludeSeniorTeamAwayFlags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include Home Flags.
        /// </summary>
        public static string DownloadItemDisplayName_IncludeSeniorTeamHomeFlags {
            get {
                return ResourceManager.GetString("DownloadItemDisplayName_IncludeSeniorTeamHomeFlags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database folder.
        /// </summary>
        public static string FormDataFolder_AdvTxtBoxDataFolder_Placeholder {
            get {
                return ResourceManager.GetString("FormDataFolder_AdvTxtBoxDataFolder_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick a folder to store the database..
        /// </summary>
        public static string FormDataFolder_DataFolderBrowserDialog_Description {
            get {
                return ResourceManager.GetString("FormDataFolder_DataFolderBrowserDialog_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database:.
        /// </summary>
        public static string FormDataFolder_GrpBoxDatabaseFolder_Text {
            get {
                return ResourceManager.GetString("FormDataFolder_GrpBoxDatabaseFolder_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database Folder.
        /// </summary>
        public static string FormDataFolder_Text {
            get {
                return ResourceManager.GetString("FormDataFolder_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string FormDownload_BtnDownload_Text {
            get {
                return ResourceManager.GetString("FormDownload_BtnDownload_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close window after successful download..
        /// </summary>
        public static string FormDownload_ChkBoxCloseOnSuccessfulDownload_Text {
            get {
                return ResourceManager.GetString("FormDownload_ChkBoxCloseOnSuccessfulDownload_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string FormDownload_Text {
            get {
                return ResourceManager.GetString("FormDownload_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} years and {1} day.
        /// </summary>
        public static string FormGeneral_AgeDay {
            get {
                return ResourceManager.GetString("FormGeneral_AgeDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} years and {1} days.
        /// </summary>
        public static string FormGeneral_AgeDays {
            get {
                return ResourceManager.GetString("FormGeneral_AgeDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string FormGeneral_BtnBrowse_Text {
            get {
                return ResourceManager.GetString("FormGeneral_BtnBrowse_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string FormGeneral_BtnCancel_Text {
            get {
                return ResourceManager.GetString("FormGeneral_BtnCancel_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string FormGeneral_BtnClose_Text {
            get {
                return ResourceManager.GetString("FormGeneral_BtnClose_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string FormGeneral_BtnOk_Text {
            get {
                return ResourceManager.GetString("FormGeneral_BtnOk_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executing tasks.
        /// </summary>
        public static string FormGenericProgress_Text {
            get {
                return ResourceManager.GetString("FormGenericProgress_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string FormMain_ToolStrpBtnDownload_Text {
            get {
                return ResourceManager.GetString("FormMain_ToolStrpBtnDownload_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opens the &apos;Download&apos; window..
        /// </summary>
        public static string FormMain_ToolStrpBtnDownload_ToolTipText {
            get {
                return ResourceManager.GetString("FormMain_ToolStrpBtnDownload_ToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Profile.
        /// </summary>
        public static string FormMain_ToolStrpBtnUser_Text {
            get {
                return ResourceManager.GetString("FormMain_ToolStrpBtnUser_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opens the &apos;User Profile&apos; window..
        /// </summary>
        public static string FormMain_ToolStrpBtnUser_ToolTipText {
            get {
                return ResourceManager.GetString("FormMain_ToolStrpBtnUser_ToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string FormMain_ToolStrpMenuItemDownload_Text {
            get {
                return ResourceManager.GetString("FormMain_ToolStrpMenuItemDownload_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string FormMain_ToolStrpMenuItemExit_Text {
            get {
                return ResourceManager.GetString("FormMain_ToolStrpMenuItemExit_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string FormMain_ToolStrpMenuItemFile_Text {
            get {
                return ResourceManager.GetString("FormMain_ToolStrpMenuItemFile_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string FormMain_ToolStrpMenuItemUser_Text {
            get {
                return ResourceManager.GetString("FormMain_ToolStrpMenuItemUser_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste the verification code generated by Hattrick..
        /// </summary>
        public static string FormToken_AdvTxtBoxVerificationCode_EmptyMessage {
            get {
                return ResourceManager.GetString("FormToken_AdvTxtBoxVerificationCode_EmptyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification code.
        /// </summary>
        public static string FormToken_AdvTxtBoxVerificationCode_Placeholder {
            get {
                return ResourceManager.GetString("FormToken_AdvTxtBoxVerificationCode_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorize.
        /// </summary>
        public static string FormToken_BtnAllowToken_Text {
            get {
                return ResourceManager.GetString("FormToken_BtnAllowToken_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check.
        /// </summary>
        public static string FormToken_BtnCheckToken_Text {
            get {
                return ResourceManager.GetString("FormToken_BtnCheckToken_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Authorization link.
        /// </summary>
        public static string FormToken_BtnGetAuthorizationLink_Text {
            get {
                return ResourceManager.GetString("FormToken_BtnGetAuthorizationLink_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revoke.
        /// </summary>
        public static string FormToken_BtnRevokeToken_Text {
            get {
                return ResourceManager.GetString("FormToken_BtnRevokeToken_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OAuth Token:.
        /// </summary>
        public static string FormToken_GrpBoxToken_Text {
            get {
                return ResourceManager.GetString("FormToken_GrpBoxToken_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorization Link.
        /// </summary>
        public static string FormToken_LnkLabelAuthorizationUrl_Text {
            get {
                return ResourceManager.GetString("FormToken_LnkLabelAuthorizationUrl_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage OAuth Token.
        /// </summary>
        public static string FormToken_Text {
            get {
                return ResourceManager.GetString("FormToken_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Token.
        /// </summary>
        public static string FormUser_BtnManageToken_Text {
            get {
                return ResourceManager.GetString("FormUser_BtnManageToken_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager:.
        /// </summary>
        public static string FormUser_GrpBoxManager_Text {
            get {
                return ResourceManager.GetString("FormUser_GrpBoxManager_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teams:.
        /// </summary>
        public static string FormUser_GrpBoxTeams_Text {
            get {
                return ResourceManager.GetString("FormUser_GrpBoxTeams_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Youth Team:.
        /// </summary>
        public static string FormUser_LblJuniorTeam_Text {
            get {
                return ResourceManager.GetString("FormUser_LblJuniorTeam_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Series:.
        /// </summary>
        public static string FormUser_LblJuniorTeamSeries_Text {
            get {
                return ResourceManager.GetString("FormUser_LblJuniorTeamSeries_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager:.
        /// </summary>
        public static string FormUser_LblManager_Text {
            get {
                return ResourceManager.GetString("FormUser_LblManager_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country:.
        /// </summary>
        public static string FormUser_LblManagerCountry_Text {
            get {
                return ResourceManager.GetString("FormUser_LblManagerCountry_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arena:.
        /// </summary>
        public static string FormUser_LblSeniorTeamArena_Text {
            get {
                return ResourceManager.GetString("FormUser_LblSeniorTeamArena_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country:.
        /// </summary>
        public static string FormUser_LblSeniorTeamCountry_Text {
            get {
                return ResourceManager.GetString("FormUser_LblSeniorTeamCountry_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to League:.
        /// </summary>
        public static string FormUser_LblSeniorTeamLeague_Text {
            get {
                return ResourceManager.GetString("FormUser_LblSeniorTeamLeague_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region:.
        /// </summary>
        public static string FormUser_LblSeniorTeamRegion_Text {
            get {
                return ResourceManager.GetString("FormUser_LblSeniorTeamRegion_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Series:.
        /// </summary>
        public static string FormUser_LblSeniorTeamSeries_Text {
            get {
                return ResourceManager.GetString("FormUser_LblSeniorTeamSeries_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supporter Tier:.
        /// </summary>
        public static string FormUser_LblSupporterTier_Text {
            get {
                return ResourceManager.GetString("FormUser_LblSupporterTier_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Profile.
        /// </summary>
        public static string FormUser_Text {
            get {
                return ResourceManager.GetString("FormUser_Text", resourceCulture);
            }
        }
    }
}
