//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hyperar.HattrickUltimate.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Denominations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Denominations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Hyperar.HattrickUltimate.Localization.Denominations", typeof(Denominations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tranquil,calm,balanced,temperamental,fiery,unstable.
        /// </summary>
        public static string AggressivenessLevel {
            get {
                return ResourceManager.GetString("AggressivenessLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nasty fellow,controversial person,pleasant guy,sympathetic guy,popular guy,beloved team member.
        /// </summary>
        public static string AgreeabilityLevel {
            get {
                return ResourceManager.GetString("AgreeabilityLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to infamous,dishonest,honest,upright,righteous,saintly.
        /// </summary>
        public static string HonestyLevel {
            get {
                return ResourceManager.GetString("HonestyLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to non-existent,disastrous,wretched,poor,weak,inadequate,passable,solid,excellent,formidable,outstanding,brilliant,magnificent,world class,supernatural,titanic,extra-terrestrial,mythical,magical,utopian,divine.
        /// </summary>
        public static string PlayerSkillLevel {
            get {
                return ResourceManager.GetString("PlayerSkillLevel", resourceCulture);
            }
        }
    }
}
