//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hyperar.HattrickUltimate.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Hyperar.HattrickUltimate.Localization.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred while attempting to perform the required action.
        ///Error message: {0}.
        /// </summary>
        public static string AnErrorHasOccurred {
            get {
                return ResourceManager.GetString("AnErrorHasOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hattrick Ultimate has been authorized successfully..
        /// </summary>
        public static string Authorized {
            get {
                return ResourceManager.GetString("Authorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hattrick is expecting an authorized OAuth Session..
        /// </summary>
        public static string AuthorizedOAuthSessionExpected {
            get {
                return ResourceManager.GetString("AuthorizedOAuthSessionExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelling....
        /// </summary>
        public static string Cancelling {
            get {
                return ResourceManager.GetString("Cancelling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred while trying to retrieve the LocalDb instance.
        /// </summary>
        public static string CannotRetrieveLocalDbInstance {
            get {
                return ResourceManager.GetString("CannotRetrieveLocalDbInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot set data folder..
        /// </summary>
        public static string CannotSetDataFolder {
            get {
                return ResourceManager.GetString("CannotSetDataFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hattrick Ultimate is able to access your account data.
        ///Since: {0} - Until: {1}..
        /// </summary>
        public static string CheckToken {
            get {
                return ResourceManager.GetString("CheckToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy to clipboard failed..
        /// </summary>
        public static string CopyToClipboardFailed {
            get {
                return ResourceManager.GetString("CopyToClipboardFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database folder:.
        /// </summary>
        public static string DatabaseFolderGroup {
            get {
                return ResourceManager.GetString("DatabaseFolderGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database folder not set. Hattrick Ultimate cannot continue..
        /// </summary>
        public static string DataFolderNotSet {
            get {
                return ResourceManager.GetString("DataFolderNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloaded &apos;{0}&apos;..
        /// </summary>
        public static string Downloaded {
            get {
                return ResourceManager.GetString("Downloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading &apos;{0}&apos;.
        /// </summary>
        public static string Downloading {
            get {
                return ResourceManager.GetString("Downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No entity of type &apos;{0}&apos; found with ID &apos;{1}&apos;..
        /// </summary>
        public static string EntityIdNotFound {
            get {
                return ResourceManager.GetString("EntityIdNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EntityState &apos;{0}&apos; not supported..
        /// </summary>
        public static string EntityStateNotSupported {
            get {
                return ResourceManager.GetString("EntityStateNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finishing….
        /// </summary>
        public static string Finishing {
            get {
                return ResourceManager.GetString("Finishing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following parameters are incompatible: {0}..
        /// </summary>
        public static string IncompatibleParameters {
            get {
                return ResourceManager.GetString("IncompatibleParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LocalDb instance not found. Hattrick Ultimate cannot continue..
        /// </summary>
        public static string LocalDbInstanceNotFound {
            get {
                return ResourceManager.GetString("LocalDbInstanceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No class of type &apos;{0}&apos; found for parameter &apos;{1}&apos;..
        /// </summary>
        public static string NotImplemented {
            get {
                return ResourceManager.GetString("NotImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter &apos;{0}&apos; has no value..
        /// </summary>
        public static string NullValueParameter {
            get {
                return ResourceManager.GetString("NullValueParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is already an active transaction on the context..
        /// </summary>
        public static string OverlappingTransaction {
            get {
                return ResourceManager.GetString("OverlappingTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procesado &apos;{0}&apos;..
        /// </summary>
        public static string Processed {
            get {
                return ResourceManager.GetString("Processed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing &apos;{0}&apos;..
        /// </summary>
        public static string Processing {
            get {
                return ResourceManager.GetString("Processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing required parameter &apos;{0}&apos;..
        /// </summary>
        public static string RequiredParameterMissing {
            get {
                return ResourceManager.GetString("RequiredParameterMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The task was cancelled..
        /// </summary>
        public static string TaskCancelled {
            get {
                return ResourceManager.GetString("TaskCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task ID must be unique..
        /// </summary>
        public static string TaskIdMustBeUnique {
            get {
                return ResourceManager.GetString("TaskIdMustBeUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task starting….
        /// </summary>
        public static string TaskStarting {
            get {
                return ResourceManager.GetString("TaskStarting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download cannot continue. At least one of your teams is playing a match..
        /// </summary>
        public static string TeamIsPlayingMatch {
            get {
                return ResourceManager.GetString("TeamIsPlayingMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is playing a match. Players data is unavailable..
        /// </summary>
        public static string TeamIsPlayingMatchCannotProcessPlayers {
            get {
                return ResourceManager.GetString("TeamIsPlayingMatchCannotProcessPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hattrick Ultimate was unauthorized successfully..
        /// </summary>
        public static string TokenRevokedSuccessfully {
            get {
                return ResourceManager.GetString("TokenRevokedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hattrick Ultimate is not authorized to access your account data..
        /// </summary>
        public static string Unauthorized {
            get {
                return ResourceManager.GetString("Unauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N/A.
        /// </summary>
        public static string UnavailableValue {
            get {
                return ResourceManager.GetString("UnavailableValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected object type..
        /// </summary>
        public static string UnexpectedObjectType {
            get {
                return ResourceManager.GetString("UnexpectedObjectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected Xml element &apos;{0}&apos;..
        /// </summary>
        public static string UnexpectedXmlElement {
            get {
                return ResourceManager.GetString("UnexpectedXmlElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown OAuth Scope &apos;{0}&apos;..
        /// </summary>
        public static string UnknownOAuthScope {
            get {
                return ResourceManager.GetString("UnknownOAuthScope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown parameter &apos;{0}&apos;..
        /// </summary>
        public static string UnknownParameter {
            get {
                return ResourceManager.GetString("UnknownParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown parameters for file &apos;{0}&apos;..
        /// </summary>
        public static string UnknownParametersForFile {
            get {
                return ResourceManager.GetString("UnknownParametersForFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Supporter Tier &apos;{0}&apos;..
        /// </summary>
        public static string UnknownSupporterTier {
            get {
                return ResourceManager.GetString("UnknownSupporterTier", resourceCulture);
            }
        }
    }
}
