//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hyperar.HattrickUltimate.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Hyperar.HattrickUltimate.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database folder.
        /// </summary>
        public static string FormDataFolder_AdvTxtBoxDataFolder_Placeholder {
            get {
                return ResourceManager.GetString("FormDataFolder_AdvTxtBoxDataFolder_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick a folder to store the database..
        /// </summary>
        public static string FormDataFolder_DataFolderBrowserDialog_Description {
            get {
                return ResourceManager.GetString("FormDataFolder_DataFolderBrowserDialog_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database.
        /// </summary>
        public static string FormDataFolder_GrpBoxDatabaseFolder_Text {
            get {
                return ResourceManager.GetString("FormDataFolder_GrpBoxDatabaseFolder_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database Folder.
        /// </summary>
        public static string FormDataFolder_Text {
            get {
                return ResourceManager.GetString("FormDataFolder_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string FormGeneral_BtnBrowse_Text {
            get {
                return ResourceManager.GetString("FormGeneral_BtnBrowse_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string FormGeneral_BtnCancel_Text {
            get {
                return ResourceManager.GetString("FormGeneral_BtnCancel_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string FormGeneral_BtnClose_Text {
            get {
                return ResourceManager.GetString("FormGeneral_BtnClose_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string FormGeneral_BtnOk_Text {
            get {
                return ResourceManager.GetString("FormGeneral_BtnOk_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste the verification code generated by Hattrick..
        /// </summary>
        public static string FormToken_AdvTxtBoxVerificationCode_EmptyMessage {
            get {
                return ResourceManager.GetString("FormToken_AdvTxtBoxVerificationCode_EmptyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification code.
        /// </summary>
        public static string FormToken_AdvTxtBoxVerificationCode_Placeholder {
            get {
                return ResourceManager.GetString("FormToken_AdvTxtBoxVerificationCode_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorize.
        /// </summary>
        public static string FormToken_BtnAllowToken_Text {
            get {
                return ResourceManager.GetString("FormToken_BtnAllowToken_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check.
        /// </summary>
        public static string FormToken_BtnCheckToken_Text {
            get {
                return ResourceManager.GetString("FormToken_BtnCheckToken_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Authorization.
        /// </summary>
        public static string FormToken_BtnOpenVerificationWebSite_Text {
            get {
                return ResourceManager.GetString("FormToken_BtnOpenVerificationWebSite_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revoke.
        /// </summary>
        public static string FormToken_BtnRevokeToken_Text {
            get {
                return ResourceManager.GetString("FormToken_BtnRevokeToken_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OAuth Token:.
        /// </summary>
        public static string FormToken_GrpBoxToken_Text {
            get {
                return ResourceManager.GetString("FormToken_GrpBoxToken_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage OAuth Token.
        /// </summary>
        public static string FormToken_Text {
            get {
                return ResourceManager.GetString("FormToken_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred while trying to retrieve the LocalDb instance.
        /// </summary>
        public static string Message_CannotRetrieveLocalDbInstance {
            get {
                return ResourceManager.GetString("Message_CannotRetrieveLocalDbInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot set data folder..
        /// </summary>
        public static string Message_CannotSetDataFolder {
            get {
                return ResourceManager.GetString("Message_CannotSetDataFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database folder:.
        /// </summary>
        public static string Message_DatabaseFolderGroup {
            get {
                return ResourceManager.GetString("Message_DatabaseFolderGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database folder not set. Hattrick Ultimate cannot continue..
        /// </summary>
        public static string Message_DataFolderNotSet {
            get {
                return ResourceManager.GetString("Message_DataFolderNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Message_Error {
            get {
                return ResourceManager.GetString("Message_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LocalDb instance not found. Hattrick Ultimate cannot continue..
        /// </summary>
        public static string Message_LocalDbInstanceNotFound {
            get {
                return ResourceManager.GetString("Message_LocalDbInstanceNotFound", resourceCulture);
            }
        }
    }
}
