//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hyperar.HattrickUltimate.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Hyperar.HattrickUltimate.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hattrick World.
        /// </summary>
        public static string DownloadItemCategory_HattrickWorld {
            get {
                return ResourceManager.GetString("DownloadItemCategory_HattrickWorld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This setting will force the download of all region of all countries instead of downloading the regions of the teams&apos; countries..
        /// </summary>
        public static string DownloadItemDescription_DescriptionDownloadAllRegions {
            get {
                return ResourceManager.GetString("DownloadItemDescription_DescriptionDownloadAllRegions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download all regions.
        /// </summary>
        public static string DownloadItemDisplayName_DownloadAllRegions {
            get {
                return ResourceManager.GetString("DownloadItemDisplayName_DownloadAllRegions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database folder.
        /// </summary>
        public static string FormDataFolder_AdvTxtBoxDataFolder_Placeholder {
            get {
                return ResourceManager.GetString("FormDataFolder_AdvTxtBoxDataFolder_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick a folder to store the database..
        /// </summary>
        public static string FormDataFolder_DataFolderBrowserDialog_Description {
            get {
                return ResourceManager.GetString("FormDataFolder_DataFolderBrowserDialog_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database:.
        /// </summary>
        public static string FormDataFolder_GrpBoxDatabaseFolder_Text {
            get {
                return ResourceManager.GetString("FormDataFolder_GrpBoxDatabaseFolder_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database Folder.
        /// </summary>
        public static string FormDataFolder_Text {
            get {
                return ResourceManager.GetString("FormDataFolder_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string FormGeneral_BtnBrowse_Text {
            get {
                return ResourceManager.GetString("FormGeneral_BtnBrowse_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string FormGeneral_BtnCancel_Text {
            get {
                return ResourceManager.GetString("FormGeneral_BtnCancel_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string FormGeneral_BtnClose_Text {
            get {
                return ResourceManager.GetString("FormGeneral_BtnClose_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string FormGeneral_BtnOk_Text {
            get {
                return ResourceManager.GetString("FormGeneral_BtnOk_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executing tasks.
        /// </summary>
        public static string FormGenericProgress_Text {
            get {
                return ResourceManager.GetString("FormGenericProgress_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste the verification code generated by Hattrick..
        /// </summary>
        public static string FormToken_AdvTxtBoxVerificationCode_EmptyMessage {
            get {
                return ResourceManager.GetString("FormToken_AdvTxtBoxVerificationCode_EmptyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification code.
        /// </summary>
        public static string FormToken_AdvTxtBoxVerificationCode_Placeholder {
            get {
                return ResourceManager.GetString("FormToken_AdvTxtBoxVerificationCode_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorize.
        /// </summary>
        public static string FormToken_BtnAllowToken_Text {
            get {
                return ResourceManager.GetString("FormToken_BtnAllowToken_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check.
        /// </summary>
        public static string FormToken_BtnCheckToken_Text {
            get {
                return ResourceManager.GetString("FormToken_BtnCheckToken_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Authorization link.
        /// </summary>
        public static string FormToken_BtnGetAuthorizationLink_Text {
            get {
                return ResourceManager.GetString("FormToken_BtnGetAuthorizationLink_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revoke.
        /// </summary>
        public static string FormToken_BtnRevokeToken_Text {
            get {
                return ResourceManager.GetString("FormToken_BtnRevokeToken_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OAuth Token:.
        /// </summary>
        public static string FormToken_GrpBoxToken_Text {
            get {
                return ResourceManager.GetString("FormToken_GrpBoxToken_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorization Link.
        /// </summary>
        public static string FormToken_LnkLabelAuthorizationUrl_Text {
            get {
                return ResourceManager.GetString("FormToken_LnkLabelAuthorizationUrl_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage OAuth Token.
        /// </summary>
        public static string FormToken_Text {
            get {
                return ResourceManager.GetString("FormToken_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Token.
        /// </summary>
        public static string FormUser_BtnManageToken_Text {
            get {
                return ResourceManager.GetString("FormUser_BtnManageToken_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager:.
        /// </summary>
        public static string FormUser_GrpBoxManager_Text {
            get {
                return ResourceManager.GetString("FormUser_GrpBoxManager_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teams:.
        /// </summary>
        public static string FormUser_GrpBoxTeams_Text {
            get {
                return ResourceManager.GetString("FormUser_GrpBoxTeams_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Youth Team:.
        /// </summary>
        public static string FormUser_LblJuniorTeam_Text {
            get {
                return ResourceManager.GetString("FormUser_LblJuniorTeam_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Series:.
        /// </summary>
        public static string FormUser_LblJuniorTeamSeries_Text {
            get {
                return ResourceManager.GetString("FormUser_LblJuniorTeamSeries_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager:.
        /// </summary>
        public static string FormUser_LblManager_Text {
            get {
                return ResourceManager.GetString("FormUser_LblManager_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country:.
        /// </summary>
        public static string FormUser_LblManagerCountry_Text {
            get {
                return ResourceManager.GetString("FormUser_LblManagerCountry_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arena:.
        /// </summary>
        public static string FormUser_LblSeniorTeamArena_Text {
            get {
                return ResourceManager.GetString("FormUser_LblSeniorTeamArena_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country:.
        /// </summary>
        public static string FormUser_LblSeniorTeamCountry_Text {
            get {
                return ResourceManager.GetString("FormUser_LblSeniorTeamCountry_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to League:.
        /// </summary>
        public static string FormUser_LblSeniorTeamLeague_Text {
            get {
                return ResourceManager.GetString("FormUser_LblSeniorTeamLeague_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region:.
        /// </summary>
        public static string FormUser_LblSeniorTeamRegion_Text {
            get {
                return ResourceManager.GetString("FormUser_LblSeniorTeamRegion_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Series:.
        /// </summary>
        public static string FormUser_LblSeniorTeamSeries_Text {
            get {
                return ResourceManager.GetString("FormUser_LblSeniorTeamSeries_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supporter Tier:.
        /// </summary>
        public static string FormUser_LblSupporterTier_Text {
            get {
                return ResourceManager.GetString("FormUser_LblSupporterTier_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string FormUser_Text {
            get {
                return ResourceManager.GetString("FormUser_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred while attempting to perform the required action.
        ///Error message: {0}.
        /// </summary>
        public static string Message_AnErrorHasOccurred {
            get {
                return ResourceManager.GetString("Message_AnErrorHasOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hattrick Ultimate has been authorized successfully..
        /// </summary>
        public static string Message_Authorized {
            get {
                return ResourceManager.GetString("Message_Authorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hattrick is expecting an authorized OAuth Session..
        /// </summary>
        public static string Message_AuthorizedOAuthSessionExpected {
            get {
                return ResourceManager.GetString("Message_AuthorizedOAuthSessionExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred while trying to retrieve the LocalDb instance.
        /// </summary>
        public static string Message_CannotRetrieveLocalDbInstance {
            get {
                return ResourceManager.GetString("Message_CannotRetrieveLocalDbInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot set data folder..
        /// </summary>
        public static string Message_CannotSetDataFolder {
            get {
                return ResourceManager.GetString("Message_CannotSetDataFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hattrick Ultimate is able to access your account data.
        ///Since: {0} - Until: {1}..
        /// </summary>
        public static string Message_CheckToken {
            get {
                return ResourceManager.GetString("Message_CheckToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy to clipboard failed..
        /// </summary>
        public static string Message_CopyToClipboardFailed {
            get {
                return ResourceManager.GetString("Message_CopyToClipboardFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database folder:.
        /// </summary>
        public static string Message_DatabaseFolderGroup {
            get {
                return ResourceManager.GetString("Message_DatabaseFolderGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database folder not set. Hattrick Ultimate cannot continue..
        /// </summary>
        public static string Message_DataFolderNotSet {
            get {
                return ResourceManager.GetString("Message_DataFolderNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloaded &apos;{0}&apos;..
        /// </summary>
        public static string Message_Downloaded {
            get {
                return ResourceManager.GetString("Message_Downloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading &apos;{0}&apos;.
        /// </summary>
        public static string Message_Downloading {
            get {
                return ResourceManager.GetString("Message_Downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No entity of type &apos;{0}&apos; found with ID &apos;{1}&apos;..
        /// </summary>
        public static string Message_EntityIdNotFound {
            get {
                return ResourceManager.GetString("Message_EntityIdNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EntityState &apos;{0}&apos; not supported..
        /// </summary>
        public static string Message_EntityStateNotSupported {
            get {
                return ResourceManager.GetString("Message_EntityStateNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Message_Error {
            get {
                return ResourceManager.GetString("Message_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finishing….
        /// </summary>
        public static string Message_Finishing {
            get {
                return ResourceManager.GetString("Message_Finishing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following parameters are incompatible: {0}..
        /// </summary>
        public static string Message_IncompatibleParameters {
            get {
                return ResourceManager.GetString("Message_IncompatibleParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string Message_Information {
            get {
                return ResourceManager.GetString("Message_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LocalDb instance not found. Hattrick Ultimate cannot continue..
        /// </summary>
        public static string Message_LocalDbInstanceNotFound {
            get {
                return ResourceManager.GetString("Message_LocalDbInstanceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No class of type &apos;{0}&apos; found for parameter &apos;{1}&apos;..
        /// </summary>
        public static string Message_NotImplemented {
            get {
                return ResourceManager.GetString("Message_NotImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter &apos;{0}&apos; has no value..
        /// </summary>
        public static string Message_NullValueParameter {
            get {
                return ResourceManager.GetString("Message_NullValueParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is already an active transaction on the context..
        /// </summary>
        public static string Message_OverlappingTransaction {
            get {
                return ResourceManager.GetString("Message_OverlappingTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procesado &apos;{0}&apos;..
        /// </summary>
        public static string Message_Processed {
            get {
                return ResourceManager.GetString("Message_Processed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing &apos;{0}&apos;..
        /// </summary>
        public static string Message_Processing {
            get {
                return ResourceManager.GetString("Message_Processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing required parameter &apos;{0}&apos;..
        /// </summary>
        public static string Message_RequiredParameterMissing {
            get {
                return ResourceManager.GetString("Message_RequiredParameterMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The task was cancelled..
        /// </summary>
        public static string Message_TaskCancelled {
            get {
                return ResourceManager.GetString("Message_TaskCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task ID must be unique..
        /// </summary>
        public static string Message_TaskIdMustBeUnique {
            get {
                return ResourceManager.GetString("Message_TaskIdMustBeUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task starting….
        /// </summary>
        public static string Message_TaskStarting {
            get {
                return ResourceManager.GetString("Message_TaskStarting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is playing a match. Players data is unavailable..
        /// </summary>
        public static string Message_TeamIsPlayingMatchCannotProcessPlayers {
            get {
                return ResourceManager.GetString("Message_TeamIsPlayingMatchCannotProcessPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hattrick Ultimate was unauthorized successfully..
        /// </summary>
        public static string Message_TokenRevokedSuccessfully {
            get {
                return ResourceManager.GetString("Message_TokenRevokedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hattrick Ultimate is not authorized to access your account data..
        /// </summary>
        public static string Message_Unauthorized {
            get {
                return ResourceManager.GetString("Message_Unauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N/A.
        /// </summary>
        public static string Message_UnavailableValue {
            get {
                return ResourceManager.GetString("Message_UnavailableValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected object type..
        /// </summary>
        public static string Message_UnexpectedObjectType {
            get {
                return ResourceManager.GetString("Message_UnexpectedObjectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected Xml element &apos;{0}&apos;..
        /// </summary>
        public static string Message_UnexpectedXmlElement {
            get {
                return ResourceManager.GetString("Message_UnexpectedXmlElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown OAuth Scope &apos;{0}&apos;..
        /// </summary>
        public static string Message_UnknownOAuthScope {
            get {
                return ResourceManager.GetString("Message_UnknownOAuthScope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown parameter &apos;{0}&apos;..
        /// </summary>
        public static string Message_UnknownParameter {
            get {
                return ResourceManager.GetString("Message_UnknownParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown parameters for file &apos;{0}&apos;..
        /// </summary>
        public static string Message_UnknownParametersForFile {
            get {
                return ResourceManager.GetString("Message_UnknownParametersForFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Supporter Tier &apos;{0}&apos;..
        /// </summary>
        public static string Message_UnknownSupporterTier {
            get {
                return ResourceManager.GetString("Message_UnknownSupporterTier", resourceCulture);
            }
        }
    }
}
