// <auto-generated />
namespace Hyperar.HattrickUltimate.UserInterface
{
    partial class FormDataFolder
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.BtnOk = new System.Windows.Forms.Button();
            this.BtnCancel = new System.Windows.Forms.Button();
            this.GrpBoxDatabaseFolder = new System.Windows.Forms.GroupBox();
            this.AdvTxtBoxDataFolder = new Hyperar.HattrickUltimate.Controls.AdvancedTextBox();
            this.BtnBrowse = new System.Windows.Forms.Button();
            this.GrpBoxDatabaseFolder.SuspendLayout();
            this.SuspendLayout();
            // 
            // BtnOk
            // 
            this.BtnOk.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.BtnOk.Image = global::Hyperar.HattrickUltimate.UserInterface.Properties.Resources.Ok_16px;
            this.BtnOk.ImageAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.BtnOk.Location = new System.Drawing.Point(272, 93);
            this.BtnOk.Name = "BtnOk";
            this.BtnOk.Size = new System.Drawing.Size(100, 28);
            this.BtnOk.TabIndex = 2;
            this.BtnOk.Text = "BtnOk";
            this.BtnOk.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.BtnOk.TextImageRelation = System.Windows.Forms.TextImageRelation.ImageBeforeText;
            this.BtnOk.UseVisualStyleBackColor = true;
            this.BtnOk.Click += new System.EventHandler(this.BtnOk_Click);
            // 
            // BtnCancel
            // 
            this.BtnCancel.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.BtnCancel.DialogResult = System.Windows.Forms.DialogResult.Cancel;
            this.BtnCancel.Image = global::Hyperar.HattrickUltimate.UserInterface.Properties.Resources.Cancel_16px;
            this.BtnCancel.ImageAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.BtnCancel.Location = new System.Drawing.Point(166, 93);
            this.BtnCancel.Name = "BtnCancel";
            this.BtnCancel.Size = new System.Drawing.Size(100, 28);
            this.BtnCancel.TabIndex = 3;
            this.BtnCancel.Text = "BtnCancel";
            this.BtnCancel.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.BtnCancel.TextImageRelation = System.Windows.Forms.TextImageRelation.ImageBeforeText;
            this.BtnCancel.UseVisualStyleBackColor = true;
            this.BtnCancel.Click += new System.EventHandler(this.BtnCancel_Click);
            // 
            // GrpBoxDatabaseFolder
            // 
            this.GrpBoxDatabaseFolder.Controls.Add(this.AdvTxtBoxDataFolder);
            this.GrpBoxDatabaseFolder.Controls.Add(this.BtnBrowse);
            this.GrpBoxDatabaseFolder.Location = new System.Drawing.Point(12, 12);
            this.GrpBoxDatabaseFolder.Name = "GrpBoxDatabaseFolder";
            this.GrpBoxDatabaseFolder.Size = new System.Drawing.Size(360, 75);
            this.GrpBoxDatabaseFolder.TabIndex = 4;
            this.GrpBoxDatabaseFolder.TabStop = false;
            this.GrpBoxDatabaseFolder.Text = "GrpBoxDatabaseFolder";
            // 
            // AdvTxtBoxDataFolder
            // 
            this.AdvTxtBoxDataFolder.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.AdvTxtBoxDataFolder.BackColor = System.Drawing.SystemColors.Window;
            this.AdvTxtBoxDataFolder.Location = new System.Drawing.Point(6, 19);
            this.AdvTxtBoxDataFolder.MaxLength = 0;
            this.AdvTxtBoxDataFolder.Name = "AdvTxtBoxDataFolder";
            this.AdvTxtBoxDataFolder.Placeholder = "AdvTxtBoxDataFolder";
            this.AdvTxtBoxDataFolder.ShowPlaceholder = true;
            this.AdvTxtBoxDataFolder.Size = new System.Drawing.Size(348, 20);
            this.AdvTxtBoxDataFolder.StickyPlaceholder = true;
            this.AdvTxtBoxDataFolder.TabIndex = 7;
            // 
            // BtnBrowse
            // 
            this.BtnBrowse.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.BtnBrowse.Image = global::Hyperar.HattrickUltimate.UserInterface.Properties.Resources.OpenFolder_16px;
            this.BtnBrowse.ImageAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.BtnBrowse.Location = new System.Drawing.Point(254, 45);
            this.BtnBrowse.Name = "BtnBrowse";
            this.BtnBrowse.Size = new System.Drawing.Size(100, 24);
            this.BtnBrowse.TabIndex = 6;
            this.BtnBrowse.Text = "BtnBrowse";
            this.BtnBrowse.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.BtnBrowse.TextImageRelation = System.Windows.Forms.TextImageRelation.ImageBeforeText;
            this.BtnBrowse.UseVisualStyleBackColor = true;
            this.BtnBrowse.Click += new System.EventHandler(this.BtnBrowse_Click);
            // 
            // FormDataFolder
            // 
            this.AcceptButton = this.BtnOk;
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.AutoValidate = System.Windows.Forms.AutoValidate.EnableAllowFocusChange;
            this.CancelButton = this.BtnCancel;
            this.ClientSize = new System.Drawing.Size(384, 133);
            this.Controls.Add(this.GrpBoxDatabaseFolder);
            this.Controls.Add(this.BtnCancel);
            this.Controls.Add(this.BtnOk);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedSingle;
            this.Icon = global::Hyperar.HattrickUltimate.UserInterface.Properties.Resources.Database;
            this.MaximizeBox = false;
            this.MinimizeBox = false;
            this.MinimumSize = new System.Drawing.Size(400, 157);
            this.Name = "FormDataFolder";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "FormDataFolder";
            this.GrpBoxDatabaseFolder.ResumeLayout(false);
            this.GrpBoxDatabaseFolder.PerformLayout();
            this.ResumeLayout(false);

        }

        #endregion
        private System.Windows.Forms.Button BtnOk;
        private System.Windows.Forms.Button BtnCancel;
        private System.Windows.Forms.GroupBox GrpBoxDatabaseFolder;
        private Controls.AdvancedTextBox AdvTxtBoxDataFolder;
        private System.Windows.Forms.Button BtnBrowse;
    }
}