// <auto-generated />
namespace Hyperar.HattrickUltimate.UserInterface
{
    partial class FormGenericProgress
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.PrgBarPercentage = new System.Windows.Forms.ProgressBar();
            this.LblTask = new System.Windows.Forms.Label();
            this.SuspendLayout();
            // 
            // PrgBarPercentage
            // 
            this.PrgBarPercentage.Location = new System.Drawing.Point(12, 32);
            this.PrgBarPercentage.MarqueeAnimationSpeed = 10;
            this.PrgBarPercentage.Name = "PrgBarPercentage";
            this.PrgBarPercentage.Size = new System.Drawing.Size(460, 20);
            this.PrgBarPercentage.TabIndex = 0;
            // 
            // LblTask
            // 
            this.LblTask.Location = new System.Drawing.Point(12, 9);
            this.LblTask.Name = "LblTask";
            this.LblTask.Size = new System.Drawing.Size(460, 20);
            this.LblTask.TabIndex = 1;
            this.LblTask.Text = "LblTask";
            this.LblTask.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // 
            // FormGenericProgress
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(484, 64);
            this.ControlBox = false;
            this.Controls.Add(this.LblTask);
            this.Controls.Add(this.PrgBarPercentage);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedSingle;
            this.Icon = global::Hyperar.HattrickUltimate.UserInterface.Properties.Resources.Working;
            this.MaximizeBox = false;
            this.MinimizeBox = false;
            this.Name = "FormGenericProgress";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "FormGenericProgress";
            this.FormClosing += new System.Windows.Forms.FormClosingEventHandler(this.FormGenericProgress_FormClosing);
            this.Shown += new System.EventHandler(this.FormGenericProgress_Shown);
            this.ResumeLayout(false);

        }

        #endregion

        private System.Windows.Forms.ProgressBar PrgBarPercentage;
        private System.Windows.Forms.Label LblTask;
    }
}