// <auto-generated />
namespace Hyperar.HattrickUltimate.UserInterface
{
    partial class FormUser
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.BtnClose = new System.Windows.Forms.Button();
            this.GrpBoxManager = new System.Windows.Forms.GroupBox();
            this.TabLayPanManager = new System.Windows.Forms.TableLayoutPanel();
            this.LblManagerCountryValue = new System.Windows.Forms.Label();
            this.LblManagerCountry = new System.Windows.Forms.Label();
            this.LblSupporterTierValue = new System.Windows.Forms.Label();
            this.LblSupporterTier = new System.Windows.Forms.Label();
            this.LblManagerValue = new System.Windows.Forms.Label();
            this.LblManager = new System.Windows.Forms.Label();
            this.GrpBoxTeams = new System.Windows.Forms.GroupBox();
            this.TabLayPanTeams = new System.Windows.Forms.TableLayoutPanel();
            this.LblJuniorTeamSeries = new System.Windows.Forms.Label();
            this.LblJuniorTeamSeriesValue = new System.Windows.Forms.Label();
            this.LblSeniorTeamArena = new System.Windows.Forms.Label();
            this.LblSeniorTeamArenaValue = new System.Windows.Forms.Label();
            this.LblSeniorTeamCountry = new System.Windows.Forms.Label();
            this.LblSeniorTeamCountryValue = new System.Windows.Forms.Label();
            this.LblSeniorTeamRegion = new System.Windows.Forms.Label();
            this.LblSeniorTeamRegionValue = new System.Windows.Forms.Label();
            this.LblSeniorTeamLeague = new System.Windows.Forms.Label();
            this.LblSeniorTeamLeagueValue = new System.Windows.Forms.Label();
            this.LblSeniorTeamSeries = new System.Windows.Forms.Label();
            this.LblSeniorTeamSeriesValue = new System.Windows.Forms.Label();
            this.LblJuniorTeam = new System.Windows.Forms.Label();
            this.LblJuniorTeamValue = new System.Windows.Forms.Label();
            this.CmbBoxTeam = new System.Windows.Forms.ComboBox();
            this.BtnManageToken = new System.Windows.Forms.Button();
            this.GrpBoxManager.SuspendLayout();
            this.TabLayPanManager.SuspendLayout();
            this.GrpBoxTeams.SuspendLayout();
            this.TabLayPanTeams.SuspendLayout();
            this.SuspendLayout();
            // 
            // BtnClose
            // 
            this.BtnClose.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.BtnClose.Image = global::Hyperar.HattrickUltimate.UserInterface.Properties.Resources.Close_16px;
            this.BtnClose.ImageAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.BtnClose.Location = new System.Drawing.Point(322, 299);
            this.BtnClose.Name = "BtnClose";
            this.BtnClose.Size = new System.Drawing.Size(100, 28);
            this.BtnClose.TabIndex = 3;
            this.BtnClose.Text = "BtnClose";
            this.BtnClose.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.BtnClose.TextImageRelation = System.Windows.Forms.TextImageRelation.ImageBeforeText;
            this.BtnClose.UseVisualStyleBackColor = true;
            this.BtnClose.Click += new System.EventHandler(this.BtnClose_Click);
            // 
            // GrpBoxManager
            // 
            this.GrpBoxManager.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.GrpBoxManager.Controls.Add(this.TabLayPanManager);
            this.GrpBoxManager.Location = new System.Drawing.Point(13, 13);
            this.GrpBoxManager.Name = "GrpBoxManager";
            this.GrpBoxManager.Size = new System.Drawing.Size(409, 85);
            this.GrpBoxManager.TabIndex = 0;
            this.GrpBoxManager.TabStop = false;
            this.GrpBoxManager.Text = "GrpBoxManager";
            // 
            // TabLayPanManager
            // 
            this.TabLayPanManager.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.TabLayPanManager.ColumnCount = 2;
            this.TabLayPanManager.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.TabLayPanManager.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.TabLayPanManager.Controls.Add(this.LblManagerCountryValue, 1, 2);
            this.TabLayPanManager.Controls.Add(this.LblManagerCountry, 0, 2);
            this.TabLayPanManager.Controls.Add(this.LblSupporterTierValue, 1, 1);
            this.TabLayPanManager.Controls.Add(this.LblSupporterTier, 0, 1);
            this.TabLayPanManager.Controls.Add(this.LblManagerValue, 1, 0);
            this.TabLayPanManager.Controls.Add(this.LblManager, 0, 0);
            this.TabLayPanManager.Location = new System.Drawing.Point(6, 19);
            this.TabLayPanManager.Name = "TabLayPanManager";
            this.TabLayPanManager.RowCount = 3;
            this.TabLayPanManager.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 20F));
            this.TabLayPanManager.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 20F));
            this.TabLayPanManager.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 20F));
            this.TabLayPanManager.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 20F));
            this.TabLayPanManager.Size = new System.Drawing.Size(397, 60);
            this.TabLayPanManager.TabIndex = 0;
            // 
            // LblManagerCountryValue
            // 
            this.LblManagerCountryValue.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.LblManagerCountryValue.Location = new System.Drawing.Point(201, 40);
            this.LblManagerCountryValue.Name = "LblManagerCountryValue";
            this.LblManagerCountryValue.Size = new System.Drawing.Size(193, 20);
            this.LblManagerCountryValue.TabIndex = 5;
            this.LblManagerCountryValue.Text = "LblManagerCountryValue";
            this.LblManagerCountryValue.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            // 
            // LblManagerCountry
            // 
            this.LblManagerCountry.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.LblManagerCountry.Location = new System.Drawing.Point(3, 40);
            this.LblManagerCountry.Name = "LblManagerCountry";
            this.LblManagerCountry.Size = new System.Drawing.Size(192, 20);
            this.LblManagerCountry.TabIndex = 4;
            this.LblManagerCountry.Text = "LblManagerCountry";
            this.LblManagerCountry.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // 
            // LblSupporterTierValue
            // 
            this.LblSupporterTierValue.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.LblSupporterTierValue.Location = new System.Drawing.Point(201, 20);
            this.LblSupporterTierValue.Name = "LblSupporterTierValue";
            this.LblSupporterTierValue.Size = new System.Drawing.Size(193, 20);
            this.LblSupporterTierValue.TabIndex = 3;
            this.LblSupporterTierValue.Text = "LblSupporterTierValue";
            this.LblSupporterTierValue.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            // 
            // LblSupporterTier
            // 
            this.LblSupporterTier.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.LblSupporterTier.Location = new System.Drawing.Point(3, 20);
            this.LblSupporterTier.Name = "LblSupporterTier";
            this.LblSupporterTier.Size = new System.Drawing.Size(192, 20);
            this.LblSupporterTier.TabIndex = 2;
            this.LblSupporterTier.Text = "LblSupporterTier";
            this.LblSupporterTier.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // 
            // LblManagerValue
            // 
            this.LblManagerValue.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.LblManagerValue.Location = new System.Drawing.Point(201, 0);
            this.LblManagerValue.Name = "LblManagerValue";
            this.LblManagerValue.Size = new System.Drawing.Size(193, 20);
            this.LblManagerValue.TabIndex = 1;
            this.LblManagerValue.Text = "LblManagerValue";
            this.LblManagerValue.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            // 
            // LblManager
            // 
            this.LblManager.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.LblManager.Location = new System.Drawing.Point(3, 0);
            this.LblManager.Name = "LblManager";
            this.LblManager.Size = new System.Drawing.Size(192, 20);
            this.LblManager.TabIndex = 0;
            this.LblManager.Text = "LblManager";
            this.LblManager.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // 
            // GrpBoxTeams
            // 
            this.GrpBoxTeams.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.GrpBoxTeams.Controls.Add(this.TabLayPanTeams);
            this.GrpBoxTeams.Location = new System.Drawing.Point(12, 104);
            this.GrpBoxTeams.Name = "GrpBoxTeams";
            this.GrpBoxTeams.Size = new System.Drawing.Size(410, 186);
            this.GrpBoxTeams.TabIndex = 1;
            this.GrpBoxTeams.TabStop = false;
            this.GrpBoxTeams.Text = "GrpBoxTeams";
            // 
            // TabLayPanTeams
            // 
            this.TabLayPanTeams.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.TabLayPanTeams.ColumnCount = 2;
            this.TabLayPanTeams.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.TabLayPanTeams.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.TabLayPanTeams.Controls.Add(this.LblJuniorTeamSeries, 0, 7);
            this.TabLayPanTeams.Controls.Add(this.LblJuniorTeamSeriesValue, 0, 7);
            this.TabLayPanTeams.Controls.Add(this.LblSeniorTeamArena, 0, 1);
            this.TabLayPanTeams.Controls.Add(this.LblSeniorTeamArenaValue, 1, 1);
            this.TabLayPanTeams.Controls.Add(this.LblSeniorTeamCountry, 0, 2);
            this.TabLayPanTeams.Controls.Add(this.LblSeniorTeamCountryValue, 1, 2);
            this.TabLayPanTeams.Controls.Add(this.LblSeniorTeamRegion, 0, 3);
            this.TabLayPanTeams.Controls.Add(this.LblSeniorTeamRegionValue, 1, 3);
            this.TabLayPanTeams.Controls.Add(this.LblSeniorTeamLeague, 0, 4);
            this.TabLayPanTeams.Controls.Add(this.LblSeniorTeamLeagueValue, 1, 4);
            this.TabLayPanTeams.Controls.Add(this.LblSeniorTeamSeries, 0, 5);
            this.TabLayPanTeams.Controls.Add(this.LblSeniorTeamSeriesValue, 1, 5);
            this.TabLayPanTeams.Controls.Add(this.LblJuniorTeam, 0, 6);
            this.TabLayPanTeams.Controls.Add(this.LblJuniorTeamValue, 1, 6);
            this.TabLayPanTeams.Controls.Add(this.CmbBoxTeam, 0, 0);
            this.TabLayPanTeams.Location = new System.Drawing.Point(6, 19);
            this.TabLayPanTeams.Name = "TabLayPanTeams";
            this.TabLayPanTeams.RowCount = 8;
            this.TabLayPanTeams.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.TabLayPanTeams.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 20F));
            this.TabLayPanTeams.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 20F));
            this.TabLayPanTeams.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 20F));
            this.TabLayPanTeams.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 20F));
            this.TabLayPanTeams.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 20F));
            this.TabLayPanTeams.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 20F));
            this.TabLayPanTeams.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 20F));
            this.TabLayPanTeams.Size = new System.Drawing.Size(398, 161);
            this.TabLayPanTeams.TabIndex = 0;
            // 
            // LblJuniorTeamSeries
            // 
            this.LblJuniorTeamSeries.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.LblJuniorTeamSeries.Location = new System.Drawing.Point(3, 141);
            this.LblJuniorTeamSeries.Name = "LblJuniorTeamSeries";
            this.LblJuniorTeamSeries.Size = new System.Drawing.Size(193, 20);
            this.LblJuniorTeamSeries.TabIndex = 13;
            this.LblJuniorTeamSeries.Text = "LblJuniorTeamSeries";
            this.LblJuniorTeamSeries.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // 
            // LblJuniorTeamSeriesValue
            // 
            this.LblJuniorTeamSeriesValue.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.LblJuniorTeamSeriesValue.Location = new System.Drawing.Point(202, 141);
            this.LblJuniorTeamSeriesValue.Name = "LblJuniorTeamSeriesValue";
            this.LblJuniorTeamSeriesValue.Size = new System.Drawing.Size(193, 20);
            this.LblJuniorTeamSeriesValue.TabIndex = 14;
            this.LblJuniorTeamSeriesValue.Text = "LblJuniorTeamSeriesValue";
            this.LblJuniorTeamSeriesValue.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            // 
            // LblSeniorTeamArena
            // 
            this.LblSeniorTeamArena.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.LblSeniorTeamArena.Location = new System.Drawing.Point(3, 21);
            this.LblSeniorTeamArena.Name = "LblSeniorTeamArena";
            this.LblSeniorTeamArena.Size = new System.Drawing.Size(193, 20);
            this.LblSeniorTeamArena.TabIndex = 1;
            this.LblSeniorTeamArena.Text = "LblSeniorTeamArena";
            this.LblSeniorTeamArena.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // 
            // LblSeniorTeamArenaValue
            // 
            this.LblSeniorTeamArenaValue.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.LblSeniorTeamArenaValue.Location = new System.Drawing.Point(202, 21);
            this.LblSeniorTeamArenaValue.Name = "LblSeniorTeamArenaValue";
            this.LblSeniorTeamArenaValue.Size = new System.Drawing.Size(193, 20);
            this.LblSeniorTeamArenaValue.TabIndex = 2;
            this.LblSeniorTeamArenaValue.Text = "LblSeniorTeamArenaValue";
            this.LblSeniorTeamArenaValue.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            // 
            // LblSeniorTeamCountry
            // 
            this.LblSeniorTeamCountry.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.LblSeniorTeamCountry.Location = new System.Drawing.Point(3, 41);
            this.LblSeniorTeamCountry.Name = "LblSeniorTeamCountry";
            this.LblSeniorTeamCountry.Size = new System.Drawing.Size(193, 20);
            this.LblSeniorTeamCountry.TabIndex = 3;
            this.LblSeniorTeamCountry.Text = "LblSeniorTeamCountry";
            this.LblSeniorTeamCountry.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // 
            // LblSeniorTeamCountryValue
            // 
            this.LblSeniorTeamCountryValue.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.LblSeniorTeamCountryValue.Location = new System.Drawing.Point(202, 41);
            this.LblSeniorTeamCountryValue.Name = "LblSeniorTeamCountryValue";
            this.LblSeniorTeamCountryValue.Size = new System.Drawing.Size(193, 20);
            this.LblSeniorTeamCountryValue.TabIndex = 4;
            this.LblSeniorTeamCountryValue.Text = "LblSeniorTeamCountryValue";
            this.LblSeniorTeamCountryValue.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            // 
            // LblSeniorTeamRegion
            // 
            this.LblSeniorTeamRegion.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.LblSeniorTeamRegion.Location = new System.Drawing.Point(3, 61);
            this.LblSeniorTeamRegion.Name = "LblSeniorTeamRegion";
            this.LblSeniorTeamRegion.Size = new System.Drawing.Size(193, 20);
            this.LblSeniorTeamRegion.TabIndex = 5;
            this.LblSeniorTeamRegion.Text = "LblSeniorTeamRegion";
            this.LblSeniorTeamRegion.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // 
            // LblSeniorTeamRegionValue
            // 
            this.LblSeniorTeamRegionValue.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.LblSeniorTeamRegionValue.Location = new System.Drawing.Point(202, 61);
            this.LblSeniorTeamRegionValue.Name = "LblSeniorTeamRegionValue";
            this.LblSeniorTeamRegionValue.Size = new System.Drawing.Size(193, 20);
            this.LblSeniorTeamRegionValue.TabIndex = 6;
            this.LblSeniorTeamRegionValue.Text = "LblSeniorTeamRegionValue";
            this.LblSeniorTeamRegionValue.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            // 
            // LblSeniorTeamLeague
            // 
            this.LblSeniorTeamLeague.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.LblSeniorTeamLeague.Location = new System.Drawing.Point(3, 81);
            this.LblSeniorTeamLeague.Name = "LblSeniorTeamLeague";
            this.LblSeniorTeamLeague.Size = new System.Drawing.Size(193, 20);
            this.LblSeniorTeamLeague.TabIndex = 7;
            this.LblSeniorTeamLeague.Text = "LblSeniorTeamLeague";
            this.LblSeniorTeamLeague.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // 
            // LblSeniorTeamLeagueValue
            // 
            this.LblSeniorTeamLeagueValue.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.LblSeniorTeamLeagueValue.Location = new System.Drawing.Point(202, 81);
            this.LblSeniorTeamLeagueValue.Name = "LblSeniorTeamLeagueValue";
            this.LblSeniorTeamLeagueValue.Size = new System.Drawing.Size(193, 20);
            this.LblSeniorTeamLeagueValue.TabIndex = 8;
            this.LblSeniorTeamLeagueValue.Text = "LblSeniorTeamLeagueValue";
            this.LblSeniorTeamLeagueValue.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            // 
            // LblSeniorTeamSeries
            // 
            this.LblSeniorTeamSeries.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.LblSeniorTeamSeries.Location = new System.Drawing.Point(3, 101);
            this.LblSeniorTeamSeries.Name = "LblSeniorTeamSeries";
            this.LblSeniorTeamSeries.Size = new System.Drawing.Size(193, 20);
            this.LblSeniorTeamSeries.TabIndex = 9;
            this.LblSeniorTeamSeries.Text = "LblSeniorTeamSeries";
            this.LblSeniorTeamSeries.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // 
            // LblSeniorTeamSeriesValue
            // 
            this.LblSeniorTeamSeriesValue.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.LblSeniorTeamSeriesValue.Location = new System.Drawing.Point(202, 101);
            this.LblSeniorTeamSeriesValue.Name = "LblSeniorTeamSeriesValue";
            this.LblSeniorTeamSeriesValue.Size = new System.Drawing.Size(193, 20);
            this.LblSeniorTeamSeriesValue.TabIndex = 10;
            this.LblSeniorTeamSeriesValue.Text = "LblSeniorTeamSeriesValue";
            this.LblSeniorTeamSeriesValue.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            // 
            // LblJuniorTeam
            // 
            this.LblJuniorTeam.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.LblJuniorTeam.Location = new System.Drawing.Point(3, 121);
            this.LblJuniorTeam.Name = "LblJuniorTeam";
            this.LblJuniorTeam.Size = new System.Drawing.Size(193, 20);
            this.LblJuniorTeam.TabIndex = 11;
            this.LblJuniorTeam.Text = "LblJuniorTeam";
            this.LblJuniorTeam.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // 
            // LblJuniorTeamValue
            // 
            this.LblJuniorTeamValue.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.LblJuniorTeamValue.Location = new System.Drawing.Point(202, 121);
            this.LblJuniorTeamValue.Name = "LblJuniorTeamValue";
            this.LblJuniorTeamValue.Size = new System.Drawing.Size(193, 20);
            this.LblJuniorTeamValue.TabIndex = 12;
            this.LblJuniorTeamValue.Text = "LblJuniorTeamValue";
            this.LblJuniorTeamValue.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            // 
            // CmbBoxTeam
            // 
            this.CmbBoxTeam.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.TabLayPanTeams.SetColumnSpan(this.CmbBoxTeam, 2);
            this.CmbBoxTeam.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.CmbBoxTeam.FormattingEnabled = true;
            this.CmbBoxTeam.Location = new System.Drawing.Point(0, 0);
            this.CmbBoxTeam.Margin = new System.Windows.Forms.Padding(0);
            this.CmbBoxTeam.Name = "CmbBoxTeam";
            this.CmbBoxTeam.Size = new System.Drawing.Size(398, 21);
            this.CmbBoxTeam.TabIndex = 0;
            this.CmbBoxTeam.SelectedIndexChanged += new System.EventHandler(this.CmbBoxTeam_SelectedIndexChanged);
            // 
            // BtnManageToken
            // 
            this.BtnManageToken.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)));
            this.BtnManageToken.Image = global::Hyperar.HattrickUltimate.UserInterface.Properties.Resources.Token_16px;
            this.BtnManageToken.ImageAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.BtnManageToken.Location = new System.Drawing.Point(12, 299);
            this.BtnManageToken.Name = "BtnManageToken";
            this.BtnManageToken.Size = new System.Drawing.Size(120, 28);
            this.BtnManageToken.TabIndex = 2;
            this.BtnManageToken.Text = "BtnManageToken";
            this.BtnManageToken.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.BtnManageToken.TextImageRelation = System.Windows.Forms.TextImageRelation.ImageBeforeText;
            this.BtnManageToken.UseVisualStyleBackColor = true;
            this.BtnManageToken.Click += new System.EventHandler(this.BtnManageToken_Click);
            // 
            // FormUser
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(434, 339);
            this.Controls.Add(this.BtnManageToken);
            this.Controls.Add(this.GrpBoxTeams);
            this.Controls.Add(this.GrpBoxManager);
            this.Controls.Add(this.BtnClose);
            this.Icon = global::Hyperar.HattrickUltimate.UserInterface.Properties.Resources.Manager;
            this.MaximizeBox = false;
            this.MaximumSize = new System.Drawing.Size(750, 378);
            this.MinimizeBox = false;
            this.MinimumSize = new System.Drawing.Size(450, 378);
            this.Name = "FormUser";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "FormUser";
            this.Load += new System.EventHandler(this.FormUser_Load);
            this.Shown += new System.EventHandler(this.FormUser_Shown);
            this.GrpBoxManager.ResumeLayout(false);
            this.TabLayPanManager.ResumeLayout(false);
            this.GrpBoxTeams.ResumeLayout(false);
            this.TabLayPanTeams.ResumeLayout(false);
            this.ResumeLayout(false);

        }

        #endregion

        private System.Windows.Forms.Button BtnClose;
        private System.Windows.Forms.GroupBox GrpBoxManager;
        private System.Windows.Forms.TableLayoutPanel TabLayPanManager;
        private System.Windows.Forms.GroupBox GrpBoxTeams;
        private System.Windows.Forms.TableLayoutPanel TabLayPanTeams;
        private System.Windows.Forms.Button BtnManageToken;
        private System.Windows.Forms.Label LblManagerCountryValue;
        private System.Windows.Forms.Label LblManagerCountry;
        private System.Windows.Forms.Label LblSupporterTierValue;
        private System.Windows.Forms.Label LblSupporterTier;
        private System.Windows.Forms.Label LblManagerValue;
        private System.Windows.Forms.Label LblManager;
        private System.Windows.Forms.Label LblJuniorTeamSeries;
        private System.Windows.Forms.Label LblJuniorTeamSeriesValue;
        private System.Windows.Forms.Label LblSeniorTeamArena;
        private System.Windows.Forms.Label LblSeniorTeamArenaValue;
        private System.Windows.Forms.Label LblSeniorTeamCountry;
        private System.Windows.Forms.Label LblSeniorTeamCountryValue;
        private System.Windows.Forms.Label LblSeniorTeamRegion;
        private System.Windows.Forms.Label LblSeniorTeamRegionValue;
        private System.Windows.Forms.Label LblSeniorTeamLeague;
        private System.Windows.Forms.Label LblSeniorTeamLeagueValue;
        private System.Windows.Forms.Label LblSeniorTeamSeries;
        private System.Windows.Forms.Label LblSeniorTeamSeriesValue;
        private System.Windows.Forms.Label LblJuniorTeam;
        private System.Windows.Forms.Label LblJuniorTeamValue;
        private System.Windows.Forms.ComboBox CmbBoxTeam;
    }
}