// <auto-generated />
namespace Hyperar.HattrickUltimate.UserInterface
{
    partial class FormDownload
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(FormDownload));
            this.PropGridDownloadSettings = new System.Windows.Forms.PropertyGrid();
            this.BtnCancel = new System.Windows.Forms.Button();
            this.BtnDownload = new System.Windows.Forms.Button();
            this.BtnClose = new System.Windows.Forms.Button();
            this.ChkBoxCloseOnSuccessfulDownload = new System.Windows.Forms.CheckBox();
            this.PgrBarProcess = new System.Windows.Forms.ProgressBar();
            this.PgrBarCurrentTask = new System.Windows.Forms.ProgressBar();
            this.LblCurrentFile = new System.Windows.Forms.Label();
            this.LblFile = new System.Windows.Forms.Label();
            this.LblCurrentTask = new System.Windows.Forms.Label();
            this.LblTask = new System.Windows.Forms.Label();
            this.LblOverallProgress = new System.Windows.Forms.Label();
            this.tableLayoutPanel1 = new System.Windows.Forms.TableLayoutPanel();
            this.tableLayoutPanel1.SuspendLayout();
            this.SuspendLayout();
            // 
            // PropGridDownloadSettings
            // 
            this.PropGridDownloadSettings.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.PropGridDownloadSettings.LineColor = System.Drawing.SystemColors.ControlDark;
            this.PropGridDownloadSettings.Location = new System.Drawing.Point(12, 12);
            this.PropGridDownloadSettings.Name = "PropGridDownloadSettings";
            this.PropGridDownloadSettings.Size = new System.Drawing.Size(460, 260);
            this.PropGridDownloadSettings.TabIndex = 0;
            // 
            // BtnCancel
            // 
            this.BtnCancel.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)));
            this.BtnCancel.Enabled = false;
            this.BtnCancel.Image = global::Hyperar.HattrickUltimate.UserInterface.Properties.Resources.Cancel_16px;
            this.BtnCancel.ImageAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.BtnCancel.Location = new System.Drawing.Point(12, 367);
            this.BtnCancel.Name = "BtnCancel";
            this.BtnCancel.Size = new System.Drawing.Size(100, 32);
            this.BtnCancel.TabIndex = 1;
            this.BtnCancel.Text = "BtnCancel";
            this.BtnCancel.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.BtnCancel.TextImageRelation = System.Windows.Forms.TextImageRelation.ImageBeforeText;
            this.BtnCancel.UseVisualStyleBackColor = true;
            this.BtnCancel.Click += new System.EventHandler(this.BtnCancel_Click);
            // 
            // BtnDownload
            // 
            this.BtnDownload.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)));
            this.BtnDownload.Image = global::Hyperar.HattrickUltimate.UserInterface.Properties.Resources.Download_16;
            this.BtnDownload.ImageAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.BtnDownload.Location = new System.Drawing.Point(12, 367);
            this.BtnDownload.Name = "BtnDownload";
            this.BtnDownload.Size = new System.Drawing.Size(100, 32);
            this.BtnDownload.TabIndex = 2;
            this.BtnDownload.Text = "BtnDownload";
            this.BtnDownload.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.BtnDownload.TextImageRelation = System.Windows.Forms.TextImageRelation.ImageBeforeText;
            this.BtnDownload.UseVisualStyleBackColor = true;
            this.BtnDownload.Click += new System.EventHandler(this.BtnDownload_Click);
            // 
            // BtnClose
            // 
            this.BtnClose.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.BtnClose.Image = global::Hyperar.HattrickUltimate.UserInterface.Properties.Resources.Close_16px;
            this.BtnClose.ImageAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.BtnClose.Location = new System.Drawing.Point(372, 367);
            this.BtnClose.Name = "BtnClose";
            this.BtnClose.Size = new System.Drawing.Size(100, 32);
            this.BtnClose.TabIndex = 3;
            this.BtnClose.Text = "BtnClose";
            this.BtnClose.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.BtnClose.TextImageRelation = System.Windows.Forms.TextImageRelation.ImageBeforeText;
            this.BtnClose.UseVisualStyleBackColor = true;
            this.BtnClose.Click += new System.EventHandler(this.BtnClose_Click);
            // 
            // ChkBoxCloseOnSuccessfulDownload
            // 
            this.ChkBoxCloseOnSuccessfulDownload.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.ChkBoxCloseOnSuccessfulDownload.Checked = true;
            this.ChkBoxCloseOnSuccessfulDownload.CheckState = System.Windows.Forms.CheckState.Checked;
            this.ChkBoxCloseOnSuccessfulDownload.Location = new System.Drawing.Point(118, 367);
            this.ChkBoxCloseOnSuccessfulDownload.MinimumSize = new System.Drawing.Size(80, 32);
            this.ChkBoxCloseOnSuccessfulDownload.Name = "ChkBoxCloseOnSuccessfulDownload";
            this.ChkBoxCloseOnSuccessfulDownload.Size = new System.Drawing.Size(248, 32);
            this.ChkBoxCloseOnSuccessfulDownload.TabIndex = 4;
            this.ChkBoxCloseOnSuccessfulDownload.Text = "ChkBoxCloseOnSuccessfulDownload";
            this.ChkBoxCloseOnSuccessfulDownload.UseVisualStyleBackColor = true;
            // 
            // PgrBarProcess
            // 
            this.PgrBarProcess.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.tableLayoutPanel1.SetColumnSpan(this.PgrBarProcess, 4);
            this.PgrBarProcess.Location = new System.Drawing.Point(0, 66);
            this.PgrBarProcess.Margin = new System.Windows.Forms.Padding(0, 3, 0, 0);
            this.PgrBarProcess.Name = "PgrBarProcess";
            this.PgrBarProcess.Size = new System.Drawing.Size(460, 17);
            this.PgrBarProcess.TabIndex = 5;
            // 
            // PgrBarCurrentTask
            // 
            this.PgrBarCurrentTask.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.tableLayoutPanel1.SetColumnSpan(this.PgrBarCurrentTask, 4);
            this.PgrBarCurrentTask.Location = new System.Drawing.Point(0, 23);
            this.PgrBarCurrentTask.Margin = new System.Windows.Forms.Padding(0, 3, 0, 0);
            this.PgrBarCurrentTask.Name = "PgrBarCurrentTask";
            this.PgrBarCurrentTask.Size = new System.Drawing.Size(460, 17);
            this.PgrBarCurrentTask.TabIndex = 6;
            // 
            // LblCurrentFile
            // 
            this.LblCurrentFile.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.LblCurrentFile.Location = new System.Drawing.Point(0, 0);
            this.LblCurrentFile.Margin = new System.Windows.Forms.Padding(0);
            this.LblCurrentFile.Name = "LblCurrentFile";
            this.LblCurrentFile.Size = new System.Drawing.Size(100, 20);
            this.LblCurrentFile.TabIndex = 7;
            this.LblCurrentFile.Text = "LblCurrentFile";
            this.LblCurrentFile.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // 
            // LblFile
            // 
            this.LblFile.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.LblFile.Location = new System.Drawing.Point(100, 0);
            this.LblFile.Margin = new System.Windows.Forms.Padding(0);
            this.LblFile.Name = "LblFile";
            this.LblFile.Size = new System.Drawing.Size(130, 20);
            this.LblFile.TabIndex = 8;
            this.LblFile.Text = "LblFile";
            this.LblFile.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // 
            // LblCurrentTask
            // 
            this.LblCurrentTask.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.LblCurrentTask.Location = new System.Drawing.Point(230, 0);
            this.LblCurrentTask.Margin = new System.Windows.Forms.Padding(0);
            this.LblCurrentTask.Name = "LblCurrentTask";
            this.LblCurrentTask.Size = new System.Drawing.Size(100, 20);
            this.LblCurrentTask.TabIndex = 9;
            this.LblCurrentTask.Text = "LblCurrentTask";
            this.LblCurrentTask.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // 
            // LblTask
            // 
            this.LblTask.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.LblTask.Location = new System.Drawing.Point(330, 0);
            this.LblTask.Margin = new System.Windows.Forms.Padding(0);
            this.LblTask.Name = "LblTask";
            this.LblTask.Size = new System.Drawing.Size(130, 20);
            this.LblTask.TabIndex = 10;
            this.LblTask.Text = "LblTask";
            this.LblTask.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // 
            // LblOverallProgress
            // 
            this.LblOverallProgress.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.tableLayoutPanel1.SetColumnSpan(this.LblOverallProgress, 2);
            this.LblOverallProgress.Location = new System.Drawing.Point(0, 43);
            this.LblOverallProgress.Margin = new System.Windows.Forms.Padding(0, 3, 0, 0);
            this.LblOverallProgress.Name = "LblOverallProgress";
            this.LblOverallProgress.Size = new System.Drawing.Size(230, 20);
            this.LblOverallProgress.TabIndex = 11;
            this.LblOverallProgress.Text = "LblOverallProgress";
            this.LblOverallProgress.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // 
            // tableLayoutPanel1
            // 
            this.tableLayoutPanel1.ColumnCount = 4;
            this.tableLayoutPanel1.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 100F));
            this.tableLayoutPanel1.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.tableLayoutPanel1.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 100F));
            this.tableLayoutPanel1.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.tableLayoutPanel1.Controls.Add(this.LblTask, 3, 0);
            this.tableLayoutPanel1.Controls.Add(this.PgrBarProcess, 0, 3);
            this.tableLayoutPanel1.Controls.Add(this.LblOverallProgress, 0, 2);
            this.tableLayoutPanel1.Controls.Add(this.LblCurrentTask, 2, 0);
            this.tableLayoutPanel1.Controls.Add(this.PgrBarCurrentTask, 0, 1);
            this.tableLayoutPanel1.Controls.Add(this.LblCurrentFile, 0, 0);
            this.tableLayoutPanel1.Controls.Add(this.LblFile, 1, 0);
            this.tableLayoutPanel1.Location = new System.Drawing.Point(12, 278);
            this.tableLayoutPanel1.Name = "tableLayoutPanel1";
            this.tableLayoutPanel1.RowCount = 4;
            this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 20F));
            this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 20F));
            this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 23F));
            this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 20F));
            this.tableLayoutPanel1.Size = new System.Drawing.Size(460, 83);
            this.tableLayoutPanel1.TabIndex = 12;
            // 
            // FormDownload
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(484, 411);
            this.Controls.Add(this.tableLayoutPanel1);
            this.Controls.Add(this.ChkBoxCloseOnSuccessfulDownload);
            this.Controls.Add(this.BtnClose);
            this.Controls.Add(this.BtnDownload);
            this.Controls.Add(this.BtnCancel);
            this.Controls.Add(this.PropGridDownloadSettings);
            this.Icon = ((System.Drawing.Icon)(resources.GetObject("$this.Icon")));
            this.MaximizeBox = false;
            this.MaximumSize = new System.Drawing.Size(800, 450);
            this.MinimizeBox = false;
            this.MinimumSize = new System.Drawing.Size(500, 450);
            this.Name = "FormDownload";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "FormDownload";
            this.tableLayoutPanel1.ResumeLayout(false);
            this.ResumeLayout(false);

        }

        #endregion

        private System.Windows.Forms.PropertyGrid PropGridDownloadSettings;
        private System.Windows.Forms.Button BtnCancel;
        private System.Windows.Forms.Button BtnDownload;
        private System.Windows.Forms.Button BtnClose;
        private System.Windows.Forms.CheckBox ChkBoxCloseOnSuccessfulDownload;
        private System.Windows.Forms.ProgressBar PgrBarProcess;
        private System.Windows.Forms.ProgressBar PgrBarCurrentTask;
        private System.Windows.Forms.TableLayoutPanel tableLayoutPanel1;
        private System.Windows.Forms.Label LblTask;
        private System.Windows.Forms.Label LblOverallProgress;
        private System.Windows.Forms.Label LblCurrentTask;
        private System.Windows.Forms.Label LblCurrentFile;
        private System.Windows.Forms.Label LblFile;
    }
}