// <auto-generated />
namespace Hyperar.HattrickUltimate.UserInterface
{
    partial class FormToken
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            this.GrpBoxToken = new System.Windows.Forms.GroupBox();
            this.BtnCopyAuthorizationLink = new System.Windows.Forms.Button();
            this.LnkLblAuthorizationLink = new System.Windows.Forms.LinkLabel();
            this.BtnAllowToken = new System.Windows.Forms.Button();
            this.AdvTxtBoxVerificationCode = new Hyperar.HattrickUltimate.Controls.AdvancedTextBox();
            this.BtnGetAuthorizationLink = new System.Windows.Forms.Button();
            this.BtnRevokeToken = new System.Windows.Forms.Button();
            this.BtnCheckToken = new System.Windows.Forms.Button();
            this.BtnClose = new System.Windows.Forms.Button();
            this.ErrProvToken = new System.Windows.Forms.ErrorProvider(this.components);
            this.GrpBoxToken.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.ErrProvToken)).BeginInit();
            this.SuspendLayout();
            // 
            // GrpBoxToken
            // 
            this.GrpBoxToken.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.GrpBoxToken.Controls.Add(this.BtnCopyAuthorizationLink);
            this.GrpBoxToken.Controls.Add(this.LnkLblAuthorizationLink);
            this.GrpBoxToken.Controls.Add(this.BtnAllowToken);
            this.GrpBoxToken.Controls.Add(this.AdvTxtBoxVerificationCode);
            this.GrpBoxToken.Controls.Add(this.BtnGetAuthorizationLink);
            this.GrpBoxToken.Location = new System.Drawing.Point(12, 12);
            this.GrpBoxToken.Name = "GrpBoxToken";
            this.GrpBoxToken.Size = new System.Drawing.Size(435, 135);
            this.GrpBoxToken.TabIndex = 0;
            this.GrpBoxToken.TabStop = false;
            this.GrpBoxToken.Text = "GrpBoxToken";
            // 
            // BtnCopyAuthorizationUrl
            // 
            this.BtnCopyAuthorizationLink.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.BtnCopyAuthorizationLink.Image = global::Hyperar.HattrickUltimate.UserInterface.Properties.Resources.CopyAuthorizationLink_16px;
            this.BtnCopyAuthorizationLink.Location = new System.Drawing.Point(405, 49);
            this.BtnCopyAuthorizationLink.Name = "BtnCopyAuthorizationUrl";
            this.BtnCopyAuthorizationLink.Size = new System.Drawing.Size(24, 24);
            this.BtnCopyAuthorizationLink.TabIndex = 6;
            this.BtnCopyAuthorizationLink.TextImageRelation = System.Windows.Forms.TextImageRelation.ImageBeforeText;
            this.BtnCopyAuthorizationLink.UseVisualStyleBackColor = true;
            this.BtnCopyAuthorizationLink.Click += new System.EventHandler(this.BtnCopyAuthorizationLink_Click);
            // 
            // LnkLblAuthorizationLink
            // 
            this.LnkLblAuthorizationLink.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.LnkLblAuthorizationLink.Location = new System.Drawing.Point(6, 49);
            this.LnkLblAuthorizationLink.Margin = new System.Windows.Forms.Padding(3);
            this.LnkLblAuthorizationLink.Name = "LnkLblAuthorizationLink";
            this.LnkLblAuthorizationLink.Size = new System.Drawing.Size(393, 24);
            this.LnkLblAuthorizationLink.TabIndex = 3;
            this.LnkLblAuthorizationLink.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.LnkLblAuthorizationLink.LinkClicked += new System.Windows.Forms.LinkLabelLinkClickedEventHandler(this.LnkLblAuthorizationLink_LinkClicked);
            // 
            // BtnAllowToken
            // 
            this.BtnAllowToken.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.BtnAllowToken.Enabled = false;
            this.BtnAllowToken.Image = global::Hyperar.HattrickUltimate.UserInterface.Properties.Resources.Check_16px;
            this.BtnAllowToken.ImageAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.BtnAllowToken.Location = new System.Drawing.Point(309, 105);
            this.BtnAllowToken.Name = "BtnAllowToken";
            this.BtnAllowToken.Size = new System.Drawing.Size(120, 24);
            this.BtnAllowToken.TabIndex = 2;
            this.BtnAllowToken.Text = "BtnAllowToken";
            this.BtnAllowToken.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.BtnAllowToken.TextImageRelation = System.Windows.Forms.TextImageRelation.ImageBeforeText;
            this.BtnAllowToken.UseVisualStyleBackColor = true;
            this.BtnAllowToken.Click += new System.EventHandler(this.BtnAllowToken_Click);
            // 
            // AdvTxtBoxVerificationCode
            // 
            this.AdvTxtBoxVerificationCode.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.ErrProvToken.SetIconPadding(this.AdvTxtBoxVerificationCode, -20);
            this.AdvTxtBoxVerificationCode.Location = new System.Drawing.Point(6, 79);
            this.AdvTxtBoxVerificationCode.Name = "AdvTxtBoxVerificationCode";
            this.AdvTxtBoxVerificationCode.Placeholder = "AdvTxtBoxVerificationCode";
            this.AdvTxtBoxVerificationCode.ShowPlaceholder = true;
            this.AdvTxtBoxVerificationCode.Size = new System.Drawing.Size(423, 20);
            this.AdvTxtBoxVerificationCode.StickyPlaceholder = true;
            this.AdvTxtBoxVerificationCode.TabIndex = 1;
            this.AdvTxtBoxVerificationCode.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.AdvTxtBoxVerificationCode.TextChanged += new System.EventHandler(this.AdvTxtBoxVerificationCode_TextChanged);
            this.AdvTxtBoxVerificationCode.Validating += new System.ComponentModel.CancelEventHandler(this.AdvTxtBoxVerificationCode_Validating);
            this.AdvTxtBoxVerificationCode.Validated += new System.EventHandler(this.AdvTxtBoxVerificationCode_Validated);
            // 
            // BtnGetAuthorizationLink
            // 
            this.BtnGetAuthorizationLink.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.BtnGetAuthorizationLink.CausesValidation = false;
            this.BtnGetAuthorizationLink.Image = global::Hyperar.HattrickUltimate.UserInterface.Properties.Resources.GetAuthorizationLink_16px;
            this.BtnGetAuthorizationLink.ImageAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.BtnGetAuthorizationLink.Location = new System.Drawing.Point(6, 19);
            this.BtnGetAuthorizationLink.Name = "BtnGetAuthorizationLink";
            this.BtnGetAuthorizationLink.Size = new System.Drawing.Size(423, 24);
            this.BtnGetAuthorizationLink.TabIndex = 0;
            this.BtnGetAuthorizationLink.Text = "BtnGetAuthorizationLink";
            this.BtnGetAuthorizationLink.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.BtnGetAuthorizationLink.TextImageRelation = System.Windows.Forms.TextImageRelation.ImageBeforeText;
            this.BtnGetAuthorizationLink.UseVisualStyleBackColor = true;
            this.BtnGetAuthorizationLink.Click += new System.EventHandler(this.BtnGetAuthorizationLink_Click);
            // 
            // BtnRevokeToken
            // 
            this.BtnRevokeToken.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)));
            this.BtnRevokeToken.CausesValidation = false;
            this.BtnRevokeToken.Image = global::Hyperar.HattrickUltimate.UserInterface.Properties.Resources.Delete_16px;
            this.BtnRevokeToken.ImageAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.BtnRevokeToken.Location = new System.Drawing.Point(138, 153);
            this.BtnRevokeToken.Name = "BtnRevokeToken";
            this.BtnRevokeToken.Size = new System.Drawing.Size(120, 28);
            this.BtnRevokeToken.TabIndex = 4;
            this.BtnRevokeToken.Text = "BtnRevokeToken";
            this.BtnRevokeToken.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.BtnRevokeToken.TextImageRelation = System.Windows.Forms.TextImageRelation.ImageBeforeText;
            this.BtnRevokeToken.UseVisualStyleBackColor = true;
            this.BtnRevokeToken.Click += new System.EventHandler(this.BtnRevokeToken_Click);
            // 
            // BtnCheckToken
            // 
            this.BtnCheckToken.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)));
            this.BtnCheckToken.CausesValidation = false;
            this.BtnCheckToken.Image = global::Hyperar.HattrickUltimate.UserInterface.Properties.Resources.Refresh_16px;
            this.BtnCheckToken.ImageAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.BtnCheckToken.Location = new System.Drawing.Point(12, 153);
            this.BtnCheckToken.Name = "BtnCheckToken";
            this.BtnCheckToken.Size = new System.Drawing.Size(120, 28);
            this.BtnCheckToken.TabIndex = 3;
            this.BtnCheckToken.Text = "BtnCheckToken";
            this.BtnCheckToken.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.BtnCheckToken.TextImageRelation = System.Windows.Forms.TextImageRelation.ImageBeforeText;
            this.BtnCheckToken.UseVisualStyleBackColor = true;
            this.BtnCheckToken.Click += new System.EventHandler(this.BtnCheckToken_Click);
            // 
            // BtnClose
            // 
            this.BtnClose.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.BtnClose.CausesValidation = false;
            this.BtnClose.Image = global::Hyperar.HattrickUltimate.UserInterface.Properties.Resources.Close_16px;
            this.BtnClose.ImageAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.BtnClose.Location = new System.Drawing.Point(347, 153);
            this.BtnClose.Name = "BtnClose";
            this.BtnClose.Size = new System.Drawing.Size(100, 28);
            this.BtnClose.TabIndex = 5;
            this.BtnClose.Text = "BtnClose";
            this.BtnClose.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.BtnClose.TextImageRelation = System.Windows.Forms.TextImageRelation.ImageBeforeText;
            this.BtnClose.UseVisualStyleBackColor = true;
            this.BtnClose.Click += new System.EventHandler(this.BtnClose_Click);
            // 
            // ErrProvToken
            // 
            this.ErrProvToken.ContainerControl = this;
            this.ErrProvToken.Icon = global::Hyperar.HattrickUltimate.UserInterface.Properties.Resources.Error;
            // 
            // FormToken
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.AutoValidate = System.Windows.Forms.AutoValidate.EnableAllowFocusChange;
            this.ClientSize = new System.Drawing.Size(459, 193);
            this.Controls.Add(this.BtnClose);
            this.Controls.Add(this.BtnCheckToken);
            this.Controls.Add(this.BtnRevokeToken);
            this.Controls.Add(this.GrpBoxToken);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedSingle;
            this.Icon = global::Hyperar.HattrickUltimate.UserInterface.Properties.Resources.Token;
            this.MaximizeBox = false;
            this.MinimizeBox = false;
            this.Name = "FormToken";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "FormToken";
            this.GrpBoxToken.ResumeLayout(false);
            this.GrpBoxToken.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.ErrProvToken)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private System.Windows.Forms.GroupBox GrpBoxToken;
        private System.Windows.Forms.Button BtnAllowToken;
        private System.Windows.Forms.Button BtnCheckToken;
        private System.Windows.Forms.Button BtnRevokeToken;
        private Controls.AdvancedTextBox AdvTxtBoxVerificationCode;
        private System.Windows.Forms.Button BtnGetAuthorizationLink;
        private System.Windows.Forms.Button BtnClose;
        private System.Windows.Forms.ErrorProvider ErrProvToken;
        private System.Windows.Forms.LinkLabel LnkLblAuthorizationLink;
        private System.Windows.Forms.Button BtnCopyAuthorizationLink;
    }
}