// <auto-generated />
namespace Hyperar.HattrickUltimate.UserInterface
{
    partial class FormDownload
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(FormDownload));
            this.PropGridDownloadSettings = new System.Windows.Forms.PropertyGrid();
            this.BtnCancel = new System.Windows.Forms.Button();
            this.BtnDownload = new System.Windows.Forms.Button();
            this.BtnClose = new System.Windows.Forms.Button();
            this.ChkBoxCloseOnSuccessfulDownload = new System.Windows.Forms.CheckBox();
            this.SuspendLayout();
            // 
            // PropGridDownloadSettings
            // 
            this.PropGridDownloadSettings.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.PropGridDownloadSettings.LineColor = System.Drawing.SystemColors.ControlDark;
            this.PropGridDownloadSettings.Location = new System.Drawing.Point(12, 12);
            this.PropGridDownloadSettings.Name = "PropGridDownloadSettings";
            this.PropGridDownloadSettings.Size = new System.Drawing.Size(460, 349);
            this.PropGridDownloadSettings.TabIndex = 0;
            // 
            // BtnCancel
            // 
            this.BtnCancel.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)));
            this.BtnCancel.Enabled = false;
            this.BtnCancel.Image = global::Hyperar.HattrickUltimate.UserInterface.Properties.Resources.Cancel_16px;
            this.BtnCancel.ImageAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.BtnCancel.Location = new System.Drawing.Point(12, 367);
            this.BtnCancel.Name = "BtnCancel";
            this.BtnCancel.Size = new System.Drawing.Size(100, 32);
            this.BtnCancel.TabIndex = 1;
            this.BtnCancel.Text = "BtnCancel";
            this.BtnCancel.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.BtnCancel.TextImageRelation = System.Windows.Forms.TextImageRelation.ImageBeforeText;
            this.BtnCancel.UseVisualStyleBackColor = true;
            this.BtnCancel.Click += new System.EventHandler(this.BtnCancel_Click);
            // 
            // BtnDownload
            // 
            this.BtnDownload.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)));
            this.BtnDownload.Image = global::Hyperar.HattrickUltimate.UserInterface.Properties.Resources.Download_16;
            this.BtnDownload.ImageAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.BtnDownload.Location = new System.Drawing.Point(12, 367);
            this.BtnDownload.Name = "BtnDownload";
            this.BtnDownload.Size = new System.Drawing.Size(100, 32);
            this.BtnDownload.TabIndex = 2;
            this.BtnDownload.Text = "BtnDownload";
            this.BtnDownload.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.BtnDownload.TextImageRelation = System.Windows.Forms.TextImageRelation.ImageBeforeText;
            this.BtnDownload.UseVisualStyleBackColor = true;
            this.BtnDownload.Click += new System.EventHandler(this.BtnDownload_Click);
            // 
            // BtnClose
            // 
            this.BtnClose.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.BtnClose.Image = global::Hyperar.HattrickUltimate.UserInterface.Properties.Resources.Close_16px;
            this.BtnClose.ImageAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.BtnClose.Location = new System.Drawing.Point(372, 367);
            this.BtnClose.Name = "BtnClose";
            this.BtnClose.Size = new System.Drawing.Size(100, 32);
            this.BtnClose.TabIndex = 3;
            this.BtnClose.Text = "BtnClose";
            this.BtnClose.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.BtnClose.TextImageRelation = System.Windows.Forms.TextImageRelation.ImageBeforeText;
            this.BtnClose.UseVisualStyleBackColor = true;
            this.BtnClose.Click += new System.EventHandler(this.BtnClose_Click);
            // 
            // ChkBoxCloseOnSuccessfulDownload
            // 
            this.ChkBoxCloseOnSuccessfulDownload.AutoSize = true;
            this.ChkBoxCloseOnSuccessfulDownload.Checked = true;
            this.ChkBoxCloseOnSuccessfulDownload.CheckState = System.Windows.Forms.CheckState.Checked;
            this.ChkBoxCloseOnSuccessfulDownload.Location = new System.Drawing.Point(118, 367);
            this.ChkBoxCloseOnSuccessfulDownload.MinimumSize = new System.Drawing.Size(80, 32);
            this.ChkBoxCloseOnSuccessfulDownload.Name = "ChkBoxCloseOnSuccessfulDownload";
            this.ChkBoxCloseOnSuccessfulDownload.Size = new System.Drawing.Size(203, 32);
            this.ChkBoxCloseOnSuccessfulDownload.TabIndex = 4;
            this.ChkBoxCloseOnSuccessfulDownload.Text = "ChkBoxCloseOnSuccessfulDownload";
            this.ChkBoxCloseOnSuccessfulDownload.UseVisualStyleBackColor = true;
            // 
            // FormDownload
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(484, 411);
            this.Controls.Add(this.ChkBoxCloseOnSuccessfulDownload);
            this.Controls.Add(this.BtnClose);
            this.Controls.Add(this.BtnDownload);
            this.Controls.Add(this.BtnCancel);
            this.Controls.Add(this.PropGridDownloadSettings);
            this.Icon = ((System.Drawing.Icon)(resources.GetObject("$this.Icon")));
            this.MaximizeBox = false;
            this.MaximumSize = new System.Drawing.Size(800, 450);
            this.MinimizeBox = false;
            this.MinimumSize = new System.Drawing.Size(500, 450);
            this.Name = "FormDownload";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "FormDownload";
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private System.Windows.Forms.PropertyGrid PropGridDownloadSettings;
        private System.Windows.Forms.Button BtnCancel;
        private System.Windows.Forms.Button BtnDownload;
        private System.Windows.Forms.Button BtnClose;
        private System.Windows.Forms.CheckBox ChkBoxCloseOnSuccessfulDownload;
    }
}