// <auto-generated />
namespace Hyperar.HattrickUltimate.UserInterface
{
    partial class FormMain
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle1 = new System.Windows.Forms.DataGridViewCellStyle();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(FormMain));
            this.MnuStrpMain = new System.Windows.Forms.MenuStrip();
            this.ToolStrpMenuItemFile = new System.Windows.Forms.ToolStripMenuItem();
            this.ToolStrpMenuItemDownload = new System.Windows.Forms.ToolStripMenuItem();
            this.toolStripSeparator1 = new System.Windows.Forms.ToolStripSeparator();
            this.ToolStrpMenuItemUser = new System.Windows.Forms.ToolStripMenuItem();
            this.toolStripSeparator2 = new System.Windows.Forms.ToolStripSeparator();
            this.ToolStrpMenuItemExit = new System.Windows.Forms.ToolStripMenuItem();
            this.ToolStrpMain = new System.Windows.Forms.ToolStrip();
            this.ToolStrpBtnDownload = new System.Windows.Forms.ToolStripButton();
            this.ToolStrpBtnUser = new System.Windows.Forms.ToolStripButton();
            this.tabControl1 = new System.Windows.Forms.TabControl();
            this.tabPage1 = new System.Windows.Forms.TabPage();
            this.splitContainer1 = new System.Windows.Forms.SplitContainer();
            this.DataGridViewSeniorPlayers = new Hyperar.HattrickUltimate.Controls.DoubleBufferedDataGridView();
            this.tabPage2 = new System.Windows.Forms.TabPage();
            this.MnuStrpMain.SuspendLayout();
            this.ToolStrpMain.SuspendLayout();
            this.tabControl1.SuspendLayout();
            this.tabPage1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.splitContainer1)).BeginInit();
            this.splitContainer1.Panel1.SuspendLayout();
            this.splitContainer1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.DataGridViewSeniorPlayers)).BeginInit();
            this.SuspendLayout();
            // 
            // MnuStrpMain
            // 
            this.MnuStrpMain.Items.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.ToolStrpMenuItemFile});
            this.MnuStrpMain.LayoutStyle = System.Windows.Forms.ToolStripLayoutStyle.HorizontalStackWithOverflow;
            this.MnuStrpMain.Location = new System.Drawing.Point(0, 0);
            this.MnuStrpMain.Name = "MnuStrpMain";
            this.MnuStrpMain.Size = new System.Drawing.Size(884, 24);
            this.MnuStrpMain.TabIndex = 0;
            this.MnuStrpMain.Text = "MnuStrpMain";
            // 
            // ToolStrpMenuItemFile
            // 
            this.ToolStrpMenuItemFile.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Text;
            this.ToolStrpMenuItemFile.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.ToolStrpMenuItemDownload,
            this.toolStripSeparator1,
            this.ToolStrpMenuItemUser,
            this.toolStripSeparator2,
            this.ToolStrpMenuItemExit});
            this.ToolStrpMenuItemFile.Name = "ToolStrpMenuItemFile";
            this.ToolStrpMenuItemFile.Size = new System.Drawing.Size(136, 20);
            this.ToolStrpMenuItemFile.Text = "ToolStrpMenuItemFile";
            // 
            // ToolStrpMenuItemDownload
            // 
            this.ToolStrpMenuItemDownload.Image = global::Hyperar.HattrickUltimate.UserInterface.Properties.Resources.Download_16;
            this.ToolStrpMenuItemDownload.Name = "ToolStrpMenuItemDownload";
            this.ToolStrpMenuItemDownload.Size = new System.Drawing.Size(227, 22);
            this.ToolStrpMenuItemDownload.Text = "ToolStrpMenuItemDownload";
            this.ToolStrpMenuItemDownload.Click += new System.EventHandler(this.ToolStrpMenuItemDownload_Click);
            // 
            // toolStripSeparator1
            // 
            this.toolStripSeparator1.Name = "toolStripSeparator1";
            this.toolStripSeparator1.Size = new System.Drawing.Size(224, 6);
            // 
            // ToolStrpMenuItemUser
            // 
            this.ToolStrpMenuItemUser.Image = global::Hyperar.HattrickUltimate.UserInterface.Properties.Resources.Manager_16px;
            this.ToolStrpMenuItemUser.Name = "ToolStrpMenuItemUser";
            this.ToolStrpMenuItemUser.Size = new System.Drawing.Size(227, 22);
            this.ToolStrpMenuItemUser.Text = "ToolStrpMenuItemUser";
            this.ToolStrpMenuItemUser.Click += new System.EventHandler(this.ToolStrpMenuItemUser_Click);
            // 
            // toolStripSeparator2
            // 
            this.toolStripSeparator2.Name = "toolStripSeparator2";
            this.toolStripSeparator2.Size = new System.Drawing.Size(224, 6);
            // 
            // ToolStrpMenuItemExit
            // 
            this.ToolStrpMenuItemExit.Image = global::Hyperar.HattrickUltimate.UserInterface.Properties.Resources.Close_16px;
            this.ToolStrpMenuItemExit.Name = "ToolStrpMenuItemExit";
            this.ToolStrpMenuItemExit.Size = new System.Drawing.Size(227, 22);
            this.ToolStrpMenuItemExit.Text = "ToolStrpMenuItemExit";
            this.ToolStrpMenuItemExit.Click += new System.EventHandler(this.ToolStrpMenuItemExit_Click);
            // 
            // ToolStrpMain
            // 
            this.ToolStrpMain.Items.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.ToolStrpBtnDownload,
            this.ToolStrpBtnUser});
            this.ToolStrpMain.Location = new System.Drawing.Point(0, 24);
            this.ToolStrpMain.Name = "ToolStrpMain";
            this.ToolStrpMain.Size = new System.Drawing.Size(884, 25);
            this.ToolStrpMain.TabIndex = 1;
            this.ToolStrpMain.Text = "ToolStrpMain";
            // 
            // ToolStrpBtnDownload
            // 
            this.ToolStrpBtnDownload.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Image;
            this.ToolStrpBtnDownload.Image = global::Hyperar.HattrickUltimate.UserInterface.Properties.Resources.Download_16;
            this.ToolStrpBtnDownload.ImageTransparentColor = System.Drawing.Color.Magenta;
            this.ToolStrpBtnDownload.Name = "ToolStrpBtnDownload";
            this.ToolStrpBtnDownload.Size = new System.Drawing.Size(23, 22);
            this.ToolStrpBtnDownload.Text = "ToolStrpBtnDownload";
            this.ToolStrpBtnDownload.Click += new System.EventHandler(this.ToolStrpBtnDownload_Click);
            // 
            // ToolStrpBtnUser
            // 
            this.ToolStrpBtnUser.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Image;
            this.ToolStrpBtnUser.Image = global::Hyperar.HattrickUltimate.UserInterface.Properties.Resources.Manager_16px;
            this.ToolStrpBtnUser.ImageTransparentColor = System.Drawing.Color.Magenta;
            this.ToolStrpBtnUser.Name = "ToolStrpBtnUser";
            this.ToolStrpBtnUser.Size = new System.Drawing.Size(23, 22);
            this.ToolStrpBtnUser.Text = "ToolStrpBtnUser";
            this.ToolStrpBtnUser.Click += new System.EventHandler(this.ToolStrpBtnUser_Click);
            // 
            // tabControl1
            // 
            this.tabControl1.Controls.Add(this.tabPage1);
            this.tabControl1.Controls.Add(this.tabPage2);
            this.tabControl1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tabControl1.Location = new System.Drawing.Point(0, 49);
            this.tabControl1.Margin = new System.Windows.Forms.Padding(0);
            this.tabControl1.Name = "tabControl1";
            this.tabControl1.SelectedIndex = 0;
            this.tabControl1.Size = new System.Drawing.Size(884, 412);
            this.tabControl1.TabIndex = 2;
            // 
            // tabPage1
            // 
            this.tabPage1.Controls.Add(this.splitContainer1);
            this.tabPage1.Location = new System.Drawing.Point(4, 22);
            this.tabPage1.Margin = new System.Windows.Forms.Padding(0);
            this.tabPage1.Name = "tabPage1";
            this.tabPage1.Size = new System.Drawing.Size(876, 386);
            this.tabPage1.TabIndex = 0;
            this.tabPage1.Text = "tabPage1";
            this.tabPage1.UseVisualStyleBackColor = true;
            // 
            // splitContainer1
            // 
            this.splitContainer1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.splitContainer1.Location = new System.Drawing.Point(0, 0);
            this.splitContainer1.Margin = new System.Windows.Forms.Padding(0);
            this.splitContainer1.Name = "splitContainer1";
            // 
            // splitContainer1.Panel1
            // 
            this.splitContainer1.Panel1.Controls.Add(this.DataGridViewSeniorPlayers);
            this.splitContainer1.Size = new System.Drawing.Size(876, 386);
            this.splitContainer1.SplitterDistance = 676;
            this.splitContainer1.TabIndex = 0;
            // 
            // DataGridViewSeniorPlayers
            // 
            this.DataGridViewSeniorPlayers.AllowUserToAddRows = false;
            this.DataGridViewSeniorPlayers.AllowUserToDeleteRows = false;
            this.DataGridViewSeniorPlayers.AllowUserToOrderColumns = true;
            this.DataGridViewSeniorPlayers.AllowUserToResizeRows = false;
            dataGridViewCellStyle1.BackColor = System.Drawing.Color.WhiteSmoke;
            this.DataGridViewSeniorPlayers.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle1;
            this.DataGridViewSeniorPlayers.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
            this.DataGridViewSeniorPlayers.CellBorderStyle = System.Windows.Forms.DataGridViewCellBorderStyle.SingleVertical;
            this.DataGridViewSeniorPlayers.ColumnHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.Single;
            this.DataGridViewSeniorPlayers.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.DisableResizing;
            this.DataGridViewSeniorPlayers.Dock = System.Windows.Forms.DockStyle.Fill;
            this.DataGridViewSeniorPlayers.EditMode = System.Windows.Forms.DataGridViewEditMode.EditProgrammatically;
            this.DataGridViewSeniorPlayers.Location = new System.Drawing.Point(0, 0);
            this.DataGridViewSeniorPlayers.MultiSelect = false;
            this.DataGridViewSeniorPlayers.Name = "DataGridViewSeniorPlayers";
            this.DataGridViewSeniorPlayers.ReadOnly = true;
            this.DataGridViewSeniorPlayers.RowHeadersVisible = false;
            this.DataGridViewSeniorPlayers.RowHeadersWidthSizeMode = System.Windows.Forms.DataGridViewRowHeadersWidthSizeMode.DisableResizing;
            this.DataGridViewSeniorPlayers.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.DataGridViewSeniorPlayers.ShowCellErrors = false;
            this.DataGridViewSeniorPlayers.ShowCellToolTips = false;
            this.DataGridViewSeniorPlayers.ShowEditingIcon = false;
            this.DataGridViewSeniorPlayers.ShowRowErrors = false;
            this.DataGridViewSeniorPlayers.Size = new System.Drawing.Size(676, 386);
            this.DataGridViewSeniorPlayers.SortColumns = ((System.Collections.Generic.Dictionary<string, System.Windows.Forms.SortOrder>)(resources.GetObject("DataGridViewSeniorPlayers.SortColumns")));
            this.DataGridViewSeniorPlayers.TabIndex = 0;
            this.DataGridViewSeniorPlayers.VirtualMode = true;
            this.DataGridViewSeniorPlayers.CellFormatting += new System.Windows.Forms.DataGridViewCellFormattingEventHandler(this.DataGridViewSeniorPlayers_CellFormatting);
            this.DataGridViewSeniorPlayers.CellValueNeeded += new System.Windows.Forms.DataGridViewCellValueEventHandler(this.DataGridViewSeniorPlayers_CellValueNeeded);
            this.DataGridViewSeniorPlayers.ColumnDisplayIndexChanged += new System.Windows.Forms.DataGridViewColumnEventHandler(this.DataGridViewSeniorPlayers_ColumnDisplayIndexChanged);
            this.DataGridViewSeniorPlayers.ColumnHeaderMouseClick += new System.Windows.Forms.DataGridViewCellMouseEventHandler(this.DataGridViewSeniorPlayers_ColumnHeaderMouseClick);
            this.DataGridViewSeniorPlayers.ColumnWidthChanged += new System.Windows.Forms.DataGridViewColumnEventHandler(this.DataGridViewSeniorPlayers_ColumnWidthChanged);
            this.DataGridViewSeniorPlayers.SelectionChanged += new System.EventHandler(this.DataGridViewSeniorPlayers_SelectionChanged);
            // 
            // tabPage2
            // 
            this.tabPage2.Location = new System.Drawing.Point(4, 22);
            this.tabPage2.Name = "tabPage2";
            this.tabPage2.Padding = new System.Windows.Forms.Padding(3);
            this.tabPage2.Size = new System.Drawing.Size(876, 386);
            this.tabPage2.TabIndex = 1;
            this.tabPage2.Text = "tabPage2";
            this.tabPage2.UseVisualStyleBackColor = true;
            // 
            // FormMain
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(884, 461);
            this.Controls.Add(this.tabControl1);
            this.Controls.Add(this.ToolStrpMain);
            this.Controls.Add(this.MnuStrpMain);
            this.Icon = global::Hyperar.HattrickUltimate.UserInterface.Properties.Resources.Icon;
            this.MainMenuStrip = this.MnuStrpMain;
            this.Name = "FormMain";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "FormMain";
            this.FormClosing += new System.Windows.Forms.FormClosingEventHandler(this.FormMain_FormClosing);
            this.Load += new System.EventHandler(this.FormMain_Load);
            this.MnuStrpMain.ResumeLayout(false);
            this.MnuStrpMain.PerformLayout();
            this.ToolStrpMain.ResumeLayout(false);
            this.ToolStrpMain.PerformLayout();
            this.tabControl1.ResumeLayout(false);
            this.tabPage1.ResumeLayout(false);
            this.splitContainer1.Panel1.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.splitContainer1)).EndInit();
            this.splitContainer1.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.DataGridViewSeniorPlayers)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private System.Windows.Forms.MenuStrip MnuStrpMain;
        private System.Windows.Forms.ToolStrip ToolStrpMain;
        private System.Windows.Forms.ToolStripButton ToolStrpBtnUser;
        private System.Windows.Forms.ToolStripButton ToolStrpBtnDownload;
        private System.Windows.Forms.ToolStripMenuItem ToolStrpMenuItemFile;
        private System.Windows.Forms.ToolStripMenuItem ToolStrpMenuItemExit;
        private System.Windows.Forms.ToolStripMenuItem ToolStrpMenuItemDownload;
        private System.Windows.Forms.ToolStripSeparator toolStripSeparator1;
        private System.Windows.Forms.ToolStripMenuItem ToolStrpMenuItemUser;
        private System.Windows.Forms.ToolStripSeparator toolStripSeparator2;
        private System.Windows.Forms.TabControl tabControl1;
        private System.Windows.Forms.TabPage tabPage1;
        private System.Windows.Forms.SplitContainer splitContainer1;
        private System.Windows.Forms.TabPage tabPage2;
        private Controls.DoubleBufferedDataGridView DataGridViewSeniorPlayers;
    }
}