// <auto-generated />
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading;
using System.Windows.Forms;

namespace Hyperar.HattrickUltimate.UserInterface
{
    static class Program
    {
        /// <summary>
        /// The main entry point for the application.
        /// </summary>
        [STAThread]
        static void Main()
        {
            // In Windows sometimes CurrentUICulture doesn't match the CurrentCulture.
            // For example: es-AR is the CurrentCulture but es-MX is the CurrentUICulture.
            // In order to correctly display the language, CurrentUICulture is overriden with CurrentCulture.
            Thread.CurrentThread.CurrentUICulture = Thread.CurrentThread.CurrentCulture;

            Application.EnableVisualStyles();
            Application.SetCompatibleTextRenderingDefault(false);

            var dataFolder = Properties.Settings.Default.DataFolder;

            if (string.IsNullOrWhiteSpace(dataFolder))
            {
                using (var form = new FormDataFolder())
                {
                    if (form.ShowDialog() == DialogResult.OK)
                    {
                        dataFolder = form.DataFolder;
                    }
                    else
                    {
                        return;
                    }
                }
            }
            else
            {
                var appDataPath = Path.Combine(
                                          Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),
                                          Application.CompanyName,
                                          Application.ProductName);

                if (!Directory.Exists(appDataPath))
                {
                    Directory.CreateDirectory(appDataPath);
                }

                AppDomain.CurrentDomain.SetData(
                                           "DataDirectory",
                                           appDataPath);

                Application.Run(new FormMain());
            }
        }
    }
}
