// <auto-generated />
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

// General Information about an assembly is controlled through the following 
// set of attributes. Change these attribute values to modify the information
// associated with an assembly.
[assembly: AssemblyTitle("Hattrick Ultimate")]
[assembly: AssemblyDescription("Hattrick Ultimate Localization Assembly.")]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyCompany("Hyperar")]
[assembly: AssemblyProduct("Hattrick Ultimate")]
[assembly: AssemblyCopyright("Copyright © Hyperar 2017")]
[assembly: AssemblyTrademark("Hattrick Ultimate")]
[assembly: AssemblyCulture("")]

// Setting ComVisible to false makes the types in this assembly not visible 
// to COM components.  If you need to access a type in this assembly from 
// COM, set the ComVisible attribute to true on that type.
[assembly: ComVisible(false)]

// The following GUID is for the ID of the typelib if this project is exposed to COM
[assembly: Guid("46129115-1267-4de3-923e-07d9e1a0c9d9")]

// Version information for an assembly consists of the following four values:
//
//      Major Version
//      Minor Version 
//      Build Number
//      Revision
//
// You can specify all the values or you can default the Build and Revision Numbers 
// by using the '*' as shown below:
// [assembly: AssemblyVersion("1.0.*")]
[assembly: AssemblyVersion("2017.10.10.2036")]
[assembly: AssemblyFileVersion("2017.10.10.2036")]
