//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hyperar.HattrickUltimate.UserInterface.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Hyperar.HattrickUltimate.UserInterface.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, pick a folder for the Hattrick Ultimate database..
        /// </summary>
        internal static string AdvTxtBoxDataFolder_EmptyMessage {
            get {
                return ResourceManager.GetString("AdvTxtBoxDataFolder_EmptyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick a folder for the database....
        /// </summary>
        internal static string AdvTxtBoxDataFolder_Placeholder {
            get {
                return ResourceManager.GetString("AdvTxtBoxDataFolder_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        internal static string BtnBrowse_Text {
            get {
                return ResourceManager.GetString("BtnBrowse_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string BtnCancel_Text {
            get {
                return ResourceManager.GetString("BtnCancel_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string BtnOk_Text {
            get {
                return ResourceManager.GetString("BtnOk_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error trying to retrieve the LocalDb instance..
        /// </summary>
        internal static string CannotRetrieveLocalDbInstance {
            get {
                return ResourceManager.GetString("CannotRetrieveLocalDbInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database folder could not be set..
        /// </summary>
        internal static string CannotSetDataFolder {
            get {
                return ResourceManager.GetString("CannotSetDataFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick the folder where the Hattrick Ultimate database will be stored..
        /// </summary>
        internal static string DataFolderBrowserDialog_Description {
            get {
                return ResourceManager.GetString("DataFolderBrowserDialog_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No database folder set, Hattrick Ultimate can&apos;t continue..
        /// </summary>
        internal static string DataFolderNotSet {
            get {
                return ResourceManager.GetString("DataFolderNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, fill in the field to continue..
        /// </summary>
        internal static string EmptyErrorMessage {
            get {
                return ResourceManager.GetString("EmptyErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database folder.
        /// </summary>
        internal static string FormDataFolder_Text {
            get {
                return ResourceManager.GetString("FormDataFolder_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No LocalDb instance found. Hattrick Ultimate can&apos;t continue..
        /// </summary>
        internal static string LocalDbInstanceNotFound {
            get {
                return ResourceManager.GetString("LocalDbInstanceNotFound", resourceCulture);
            }
        }
    }
}
