-- [app].[Grid]
IF NOT EXISTS (SELECT [Id] FROM [app].[Grid] WHERE [GridType] = 0)
    INSERT INTO [app].[Grid] ([Name], [GridType]) VALUES ('Main Window Senior Player Grid', 0);

-- [app].[GridColumn]
IF NOT EXISTS (SELECT [Id] FROM [app].[GridColumn] WHERE [Name] = 'ColumnSeniorPlayerHattrickId' AND [GridId] = (SELECT [Id] FROM [app].[Grid] WHERE [GridType] = 0))
    INSERT INTO [app].[GridColumn] ( [Name],  [GridColumnType],  [ValueDenominationType],  [ValuePropertyName],  [ValueChangeTrackingPropertyName], [IsVisible], [GridId]) VALUES ('ColumnSeniorPlayerHattrickId', 0, 0, 'HattrickId', NULL, 1, (SELECT [Id] FROM [app].[Grid] WHERE [GridType] = 0));
IF NOT EXISTS (SELECT [Id] FROM [app].[GridColumn] WHERE [Name] = 'ColumnSeniorPlayerFirstName' AND [GridId] = (SELECT [Id] FROM [app].[Grid] WHERE [GridType] = 0))
    INSERT INTO [app].[GridColumn] ( [Name],  [GridColumnType],  [ValueDenominationType],  [ValuePropertyName],  [ValueChangeTrackingPropertyName], [IsVisible], [GridId]) VALUES ('ColumnSeniorPlayerFirstName', 0, 0, 'FirstName', NULL, 1, (SELECT [Id] FROM [app].[Grid] WHERE [GridType] = 0));
IF NOT EXISTS (SELECT [Id] FROM [app].[GridColumn] WHERE [Name] = 'ColumnSeniorPlayerNickName' AND [GridId] = (SELECT [Id] FROM [app].[Grid] WHERE [GridType] = 0))
    INSERT INTO [app].[GridColumn] ( [Name],  [GridColumnType],  [ValueDenominationType],  [ValuePropertyName],  [ValueChangeTrackingPropertyName], [IsVisible], [GridId]) VALUES ('ColumnSeniorPlayerNickName', 0, 0, 'NickName', NULL, 1, (SELECT [Id] FROM [app].[Grid] WHERE [GridType] = 0));
IF NOT EXISTS (SELECT [Id] FROM [app].[GridColumn] WHERE [Name] = 'ColumnSeniorPlayerLastName' AND [GridId] = (SELECT [Id] FROM [app].[Grid] WHERE [GridType] = 0))
    INSERT INTO [app].[GridColumn] ( [Name],  [GridColumnType],  [ValueDenominationType],  [ValuePropertyName],  [ValueChangeTrackingPropertyName], [IsVisible], [GridId]) VALUES ('ColumnSeniorPlayerLastName', 0, 0, 'LastName', NULL, 1, (SELECT [Id] FROM [app].[Grid] WHERE [GridType] = 0));
IF NOT EXISTS (SELECT [Id] FROM [app].[GridColumn] WHERE [Name] = 'ColumnSeniorPlayerAge' AND [GridId] = (SELECT [Id] FROM [app].[Grid] WHERE [GridType] = 0))
    INSERT INTO [app].[GridColumn] ( [Name],  [GridColumnType],  [ValueDenominationType],  [ValuePropertyName],  [ValueChangeTrackingPropertyName], [IsVisible], [GridId]) VALUES ('ColumnSeniorPlayerAge', 0, 0, 'Age', NULL, 1, (SELECT [Id] FROM [app].[Grid] WHERE [GridType] = 0));
IF NOT EXISTS (SELECT [Id] FROM [app].[GridColumn] WHERE [Name] = 'ColumnSeniorPlayerHasHomegrownBonus' AND [GridId] = (SELECT [Id] FROM [app].[Grid] WHERE [GridType] = 0))
    INSERT INTO [app].[GridColumn] ( [Name],  [GridColumnType],  [ValueDenominationType],  [ValuePropertyName],  [ValueChangeTrackingPropertyName], [IsVisible], [GridId]) VALUES ('ColumnSeniorPlayerHasHomegrownBonus', 0, 0, 'HasHomegrownBonus', NULL, 1, (SELECT [Id] FROM [app].[Grid] WHERE [GridType] = 0));
IF NOT EXISTS (SELECT [Id] FROM [app].[GridColumn] WHERE [Name] = 'ColumnSeniorPlayerAgreeability' AND [GridId] = (SELECT [Id] FROM [app].[Grid] WHERE [GridType] = 0))
    INSERT INTO [app].[GridColumn] ( [Name],  [GridColumnType],  [ValueDenominationType],  [ValuePropertyName],  [ValueChangeTrackingPropertyName], [IsVisible], [GridId]) VALUES ('ColumnSeniorPlayerAgreeability', 3, 1, 'Agreeability', NULL, 1, (SELECT [Id] FROM [app].[Grid] WHERE [GridType] = 0));
IF NOT EXISTS (SELECT [Id] FROM [app].[GridColumn] WHERE [Name] = 'ColumnSeniorPlayerAggressiveness' AND [GridId] = (SELECT [Id] FROM [app].[Grid] WHERE [GridType] = 0))
    INSERT INTO [app].[GridColumn] ( [Name],  [GridColumnType],  [ValueDenominationType],  [ValuePropertyName],  [ValueChangeTrackingPropertyName], [IsVisible], [GridId]) VALUES ('ColumnSeniorPlayerAggressiveness', 3, 2, 'Aggressiveness', NULL, 1, (SELECT [Id] FROM [app].[Grid] WHERE [GridType] = 0));
IF NOT EXISTS (SELECT [Id] FROM [app].[GridColumn] WHERE [Name] = 'ColumnSeniorPlayerHonesty' AND [GridId] = (SELECT [Id] FROM [app].[Grid] WHERE [GridType] = 0))
    INSERT INTO [app].[GridColumn] ( [Name],  [GridColumnType],  [ValueDenominationType],  [ValuePropertyName],  [ValueChangeTrackingPropertyName], [IsVisible], [GridId]) VALUES ('ColumnSeniorPlayerHonesty', 3, 3, 'Honesty', NULL, 1, (SELECT [Id] FROM [app].[Grid] WHERE [GridType] = 0));
IF NOT EXISTS (SELECT [Id] FROM [app].[GridColumn] WHERE [Name] = 'ColumnSeniorPlayerLeadership' AND [GridId] = (SELECT [Id] FROM [app].[Grid] WHERE [GridType] = 0))
    INSERT INTO [app].[GridColumn] ( [Name],  [GridColumnType],  [ValueDenominationType],  [ValuePropertyName],  [ValueChangeTrackingPropertyName], [IsVisible], [GridId]) VALUES ('ColumnSeniorPlayerLeadership', 3, 4, 'Leadership', NULL, 1, (SELECT [Id] FROM [app].[Grid] WHERE [GridType] = 0));
IF NOT EXISTS (SELECT [Id] FROM [app].[GridColumn] WHERE [Name] = 'ColumnSeniorPlayerSpecialty' AND [GridId] = (SELECT [Id] FROM [app].[Grid] WHERE [GridType] = 0))
    INSERT INTO [app].[GridColumn] ( [Name],  [GridColumnType],  [ValueDenominationType],  [ValuePropertyName],  [ValueChangeTrackingPropertyName], [IsVisible], [GridId]) VALUES ('ColumnSeniorPlayerSpecialty', 0, 0, 'Specialty', NULL, 1, (SELECT [Id] FROM [app].[Grid] WHERE [GridType] = 0));
IF NOT EXISTS (SELECT [Id] FROM [app].[GridColumn] WHERE [Name] = 'ColumnSeniorPlayerWage' AND [GridId] = (SELECT [Id] FROM [app].[Grid] WHERE [GridType] = 0))
    INSERT INTO [app].[GridColumn] ( [Name],  [GridColumnType],  [ValueDenominationType],  [ValuePropertyName],  [ValueChangeTrackingPropertyName], [IsVisible], [GridId]) VALUES ('ColumnSeniorPlayerWage', 0, 0, 'Wage', NULL, 1, (SELECT [Id] FROM [app].[Grid] WHERE [GridType] = 0));
IF NOT EXISTS (SELECT [Id] FROM [app].[GridColumn] WHERE [Name] = 'ColumnSeniorPlayerCareerGoals' AND [GridId] = (SELECT [Id] FROM [app].[Grid] WHERE [GridType] = 0))
    INSERT INTO [app].[GridColumn] ( [Name],  [GridColumnType],  [ValueDenominationType],  [ValuePropertyName],  [ValueChangeTrackingPropertyName], [IsVisible], [GridId]) VALUES ('ColumnSeniorPlayerCareerGoals', 0, 0, 'CareerGoals', NULL, 1, (SELECT [Id] FROM [app].[Grid] WHERE [GridType] = 0));
IF NOT EXISTS (SELECT [Id] FROM [app].[GridColumn] WHERE [Name] = 'ColumnSeniorPlayerCareerHattricks' AND [GridId] = (SELECT [Id] FROM [app].[Grid] WHERE [GridType] = 0))
    INSERT INTO [app].[GridColumn] ( [Name],  [GridColumnType],  [ValueDenominationType],  [ValuePropertyName],  [ValueChangeTrackingPropertyName], [IsVisible], [GridId]) VALUES ('ColumnSeniorPlayerCareerHattricks', 0, 0, 'CareerHattricks', NULL, 1, (SELECT [Id] FROM [app].[Grid] WHERE [GridType] = 0));
IF NOT EXISTS (SELECT [Id] FROM [app].[GridColumn] WHERE [Name] = 'ColumnSeniorPlayerBookingStatus' AND [GridId] = (SELECT [Id] FROM [app].[Grid] WHERE [GridType] = 0))
    INSERT INTO [app].[GridColumn] ( [Name],  [GridColumnType],  [ValueDenominationType],  [ValuePropertyName],  [ValueChangeTrackingPropertyName], [IsVisible], [GridId]) VALUES ('ColumnSeniorPlayerBookingStatus', 0, 0, 'BookingStatus', NULL, 1, (SELECT [Id] FROM [app].[Grid] WHERE [GridType] = 0));
IF NOT EXISTS (SELECT [Id] FROM [app].[GridColumn] WHERE [Name] = 'ColumnSeniorPlayerInjuryStatus' AND [GridId] = (SELECT [Id] FROM [app].[Grid] WHERE [GridType] = 0))
    INSERT INTO [app].[GridColumn] ( [Name],  [GridColumnType],  [ValueDenominationType],  [ValuePropertyName],  [ValueChangeTrackingPropertyName], [IsVisible], [GridId]) VALUES ('ColumnSeniorPlayerInjuryStatus', 0, 0, 'InjuryStatus', NULL, 1, (SELECT [Id] FROM [app].[Grid] WHERE [GridType] = 0));
IF NOT EXISTS (SELECT [Id] FROM [app].[GridColumn] WHERE [Name] = 'ColumnSeniorPlayerPlaysOnNationalTeam' AND [GridId] = (SELECT [Id] FROM [app].[Grid] WHERE [GridType] = 0))
    INSERT INTO [app].[GridColumn] ( [Name],  [GridColumnType],  [ValueDenominationType],  [ValuePropertyName],  [ValueChangeTrackingPropertyName], [IsVisible], [GridId]) VALUES ('ColumnSeniorPlayerPlaysOnNationalTeam', 0, 0, 'PlaysOnNationalTeam', NULL, 1, (SELECT [Id] FROM [app].[Grid] WHERE [GridType] = 0));
IF NOT EXISTS (SELECT [Id] FROM [app].[GridColumn] WHERE [Name] = 'ColumnSeniorPlayerIsOnTransferMarket' AND [GridId] = (SELECT [Id] FROM [app].[Grid] WHERE [GridType] = 0))
    INSERT INTO [app].[GridColumn] ( [Name],  [GridColumnType],  [ValueDenominationType],  [ValuePropertyName],  [ValueChangeTrackingPropertyName], [IsVisible], [GridId]) VALUES ('ColumnSeniorPlayerIsOnTransferMarket', 0, 0, 'IsOnTransferMarket', NULL, 1, (SELECT [Id] FROM [app].[Grid] WHERE [GridType] = 0));
IF NOT EXISTS (SELECT [Id] FROM [app].[GridColumn] WHERE [Name] = 'ColumnSeniorPlayerMatchesOnSeniorNationalTeam' AND [GridId] = (SELECT [Id] FROM [app].[Grid] WHERE [GridType] = 0))
    INSERT INTO [app].[GridColumn] ( [Name],  [GridColumnType],  [ValueDenominationType],  [ValuePropertyName],  [ValueChangeTrackingPropertyName], [IsVisible], [GridId]) VALUES ('ColumnSeniorPlayerMatchesOnSeniorNationalTeam', 0, 0, 'MatchesOnSeniorNationalTeam', NULL, 1, (SELECT [Id] FROM [app].[Grid] WHERE [GridType] = 0));
IF NOT EXISTS (SELECT [Id] FROM [app].[GridColumn] WHERE [Name] = 'ColumnSeniorPlayerMatchesOnJuniorNationalTeam' AND [GridId] = (SELECT [Id] FROM [app].[Grid] WHERE [GridType] = 0))
    INSERT INTO [app].[GridColumn] ( [Name],  [GridColumnType],  [ValueDenominationType],  [ValuePropertyName],  [ValueChangeTrackingPropertyName], [IsVisible], [GridId]) VALUES ('ColumnSeniorPlayerMatchesOnJuniorNationalTeam', 0, 0, 'MatchesOnJuniorNationalTeam', NULL, 1, (SELECT [Id] FROM [app].[Grid] WHERE [GridType] = 0));
IF NOT EXISTS (SELECT [Id] FROM [app].[GridColumn] WHERE [Name] = 'ColumnSeniorPlayerCategory' AND [GridId] = (SELECT [Id] FROM [app].[Grid] WHERE [GridType] = 0))
    INSERT INTO [app].[GridColumn] ( [Name],  [GridColumnType],  [ValueDenominationType],  [ValuePropertyName],  [ValueChangeTrackingPropertyName], [IsVisible], [GridId]) VALUES ('ColumnSeniorPlayerCategory', 0, 0, 'Category', NULL, 1, (SELECT [Id] FROM [app].[Grid] WHERE [GridType] = 0));
IF NOT EXISTS (SELECT [Id] FROM [app].[GridColumn] WHERE [Name] = 'ColumnSeniorPlayerCountryId' AND [GridId] = (SELECT [Id] FROM [app].[Grid] WHERE [GridType] = 0))
    INSERT INTO [app].[GridColumn] ( [Name],  [GridColumnType],  [ValueDenominationType],  [ValuePropertyName],  [ValueChangeTrackingPropertyName], [IsVisible], [GridId]) VALUES ('ColumnSeniorPlayerCountryId', 0, 0, 'CountryId', NULL, 1, (SELECT [Id] FROM [app].[Grid] WHERE [GridType] = 0));
IF NOT EXISTS (SELECT [Id] FROM [app].[GridColumn] WHERE [Name] = 'ColumnSeniorPlayerCountryHattrickId' AND [GridId] = (SELECT [Id] FROM [app].[Grid] WHERE [GridType] = 0))
    INSERT INTO [app].[GridColumn] ( [Name],  [GridColumnType],  [ValueDenominationType],  [ValuePropertyName],  [ValueChangeTrackingPropertyName], [IsVisible], [GridId]) VALUES ('ColumnSeniorPlayerCountryHattrickId', 0, 0, 'CountryHattrickId', NULL, 1, (SELECT [Id] FROM [app].[Grid] WHERE [GridType] = 0));
IF NOT EXISTS (SELECT [Id] FROM [app].[GridColumn] WHERE [Name] = 'ColumnSeniorPlayerCountryName' AND [GridId] = (SELECT [Id] FROM [app].[Grid] WHERE [GridType] = 0))
    INSERT INTO [app].[GridColumn] ( [Name],  [GridColumnType],  [ValueDenominationType],  [ValuePropertyName],  [ValueChangeTrackingPropertyName], [IsVisible], [GridId]) VALUES ('ColumnSeniorPlayerCountryName', 0, 0, 'CountryName', NULL, 1, (SELECT [Id] FROM [app].[Grid] WHERE [GridType] = 0));
IF NOT EXISTS (SELECT [Id] FROM [app].[GridColumn] WHERE [Name] = 'ColumnSeniorPlayerCountryEnglishName' AND [GridId] = (SELECT [Id] FROM [app].[Grid] WHERE [GridType] = 0))
    INSERT INTO [app].[GridColumn] ( [Name],  [GridColumnType],  [ValueDenominationType],  [ValuePropertyName],  [ValueChangeTrackingPropertyName], [IsVisible], [GridId]) VALUES ('ColumnSeniorPlayerCountryEnglishName', 0, 0, 'CountryEnglishName', NULL, 1, (SELECT [Id] FROM [app].[Grid] WHERE [GridType] = 0));
IF NOT EXISTS (SELECT [Id] FROM [app].[GridColumn] WHERE [Name] = 'ColumnSeniorPlayerForm' AND [GridId] = (SELECT [Id] FROM [app].[Grid] WHERE [GridType] = 0))
    INSERT INTO [app].[GridColumn] ( [Name],  [GridColumnType],  [ValueDenominationType],  [ValuePropertyName],  [ValueChangeTrackingPropertyName], [IsVisible], [GridId]) VALUES ('ColumnSeniorPlayerForm', 4, 4, 'Form', 'FormDelta', 1, (SELECT [Id] FROM [app].[Grid] WHERE [GridType] = 0));
IF NOT EXISTS (SELECT [Id] FROM [app].[GridColumn] WHERE [Name] = 'ColumnSeniorPlayerStamina' AND [GridId] = (SELECT [Id] FROM [app].[Grid] WHERE [GridType] = 0))
    INSERT INTO [app].[GridColumn] ( [Name],  [GridColumnType],  [ValueDenominationType],  [ValuePropertyName],  [ValueChangeTrackingPropertyName], [IsVisible], [GridId]) VALUES ('ColumnSeniorPlayerStamina', 4, 4, 'Stamina', 'StaminaDelta', 1, (SELECT [Id] FROM [app].[Grid] WHERE [GridType] = 0));
IF NOT EXISTS (SELECT [Id] FROM [app].[GridColumn] WHERE [Name] = 'ColumnSeniorPlayerKeeper' AND [GridId] = (SELECT [Id] FROM [app].[Grid] WHERE [GridType] = 0))
    INSERT INTO [app].[GridColumn] ( [Name],  [GridColumnType],  [ValueDenominationType],  [ValuePropertyName],  [ValueChangeTrackingPropertyName], [IsVisible], [GridId]) VALUES ('ColumnSeniorPlayerKeeper', 4, 4, 'Keeper', 'KeeperDelta', 1, (SELECT [Id] FROM [app].[Grid] WHERE [GridType] = 0));
IF NOT EXISTS (SELECT [Id] FROM [app].[GridColumn] WHERE [Name] = 'ColumnSeniorPlayerDefending' AND [GridId] = (SELECT [Id] FROM [app].[Grid] WHERE [GridType] = 0))
    INSERT INTO [app].[GridColumn] ( [Name],  [GridColumnType],  [ValueDenominationType],  [ValuePropertyName],  [ValueChangeTrackingPropertyName], [IsVisible], [GridId]) VALUES ('ColumnSeniorPlayerDefending', 4, 4, 'Defending', 'DefendingDelta', 1, (SELECT [Id] FROM [app].[Grid] WHERE [GridType] = 0));
IF NOT EXISTS (SELECT [Id] FROM [app].[GridColumn] WHERE [Name] = 'ColumnSeniorPlayerPlaymaking' AND [GridId] = (SELECT [Id] FROM [app].[Grid] WHERE [GridType] = 0))
    INSERT INTO [app].[GridColumn] ( [Name],  [GridColumnType],  [ValueDenominationType],  [ValuePropertyName],  [ValueChangeTrackingPropertyName], [IsVisible], [GridId]) VALUES ('ColumnSeniorPlayerPlaymaking', 4, 4, 'Playmaking', 'PlaymakingDelta', 1, (SELECT [Id] FROM [app].[Grid] WHERE [GridType] = 0));
IF NOT EXISTS (SELECT [Id] FROM [app].[GridColumn] WHERE [Name] = 'ColumnSeniorPlayerWinger' AND [GridId] = (SELECT [Id] FROM [app].[Grid] WHERE [GridType] = 0))
    INSERT INTO [app].[GridColumn] ( [Name],  [GridColumnType],  [ValueDenominationType],  [ValuePropertyName],  [ValueChangeTrackingPropertyName], [IsVisible], [GridId]) VALUES ('ColumnSeniorPlayerWinger', 4, 4, 'Winger', 'WingerDelta', 1, (SELECT [Id] FROM [app].[Grid] WHERE [GridType] = 0));
IF NOT EXISTS (SELECT [Id] FROM [app].[GridColumn] WHERE [Name] = 'ColumnSeniorPlayerPassing' AND [GridId] = (SELECT [Id] FROM [app].[Grid] WHERE [GridType] = 0))
    INSERT INTO [app].[GridColumn] ( [Name],  [GridColumnType],  [ValueDenominationType],  [ValuePropertyName],  [ValueChangeTrackingPropertyName], [IsVisible], [GridId]) VALUES ('ColumnSeniorPlayerPassing', 4, 4, 'Passing', 'PassingDelta', 1, (SELECT [Id] FROM [app].[Grid] WHERE [GridType] = 0));
IF NOT EXISTS (SELECT [Id] FROM [app].[GridColumn] WHERE [Name] = 'ColumnSeniorPlayerScoring' AND [GridId] = (SELECT [Id] FROM [app].[Grid] WHERE [GridType] = 0))
    INSERT INTO [app].[GridColumn] ( [Name],  [GridColumnType],  [ValueDenominationType],  [ValuePropertyName],  [ValueChangeTrackingPropertyName], [IsVisible], [GridId]) VALUES ('ColumnSeniorPlayerScoring', 4, 4, 'Scoring', 'ScoringDelta', 1, (SELECT [Id] FROM [app].[Grid] WHERE [GridType] = 0));
IF NOT EXISTS (SELECT [Id] FROM [app].[GridColumn] WHERE [Name] = 'ColumnSeniorPlayerSetPieces' AND [GridId] = (SELECT [Id] FROM [app].[Grid] WHERE [GridType] = 0))
    INSERT INTO [app].[GridColumn] ( [Name],  [GridColumnType],  [ValueDenominationType],  [ValuePropertyName],  [ValueChangeTrackingPropertyName], [IsVisible], [GridId]) VALUES ('ColumnSeniorPlayerSetPieces', 4, 4, 'SetPieces', 'SetPiecesDelta', 1, (SELECT [Id] FROM [app].[Grid] WHERE [GridType] = 0));
IF NOT EXISTS (SELECT [Id] FROM [app].[GridColumn] WHERE [Name] = 'ColumnSeniorPlayerLoyalty' AND [GridId] = (SELECT [Id] FROM [app].[Grid] WHERE [GridType] = 0))
    INSERT INTO [app].[GridColumn] ( [Name],  [GridColumnType],  [ValueDenominationType],  [ValuePropertyName],  [ValueChangeTrackingPropertyName], [IsVisible], [GridId]) VALUES ('ColumnSeniorPlayerLoyalty', 4, 4, 'Loyalty', 'LoyaltyDelta', 1, (SELECT [Id] FROM [app].[Grid] WHERE [GridType] = 0));
IF NOT EXISTS (SELECT [Id] FROM [app].[GridColumn] WHERE [Name] = 'ColumnSeniorPlayerExperience' AND [GridId] = (SELECT [Id] FROM [app].[Grid] WHERE [GridType] = 0))
    INSERT INTO [app].[GridColumn] ( [Name],  [GridColumnType],  [ValueDenominationType],  [ValuePropertyName],  [ValueChangeTrackingPropertyName], [IsVisible], [GridId]) VALUES ('ColumnSeniorPlayerExperience', 4, 4, 'Experience', 'ExperienceDelta', 1, (SELECT [Id] FROM [app].[Grid] WHERE [GridType] = 0));
IF NOT EXISTS (SELECT [Id] FROM [app].[GridColumn] WHERE [Name] = 'ColumnSeniorPlayerTotalSkillIndex' AND [GridId] = (SELECT [Id] FROM [app].[Grid] WHERE [GridType] = 0))
    INSERT INTO [app].[GridColumn] ( [Name],  [GridColumnType],  [ValueDenominationType],  [ValuePropertyName],  [ValueChangeTrackingPropertyName], [IsVisible], [GridId]) VALUES ('ColumnSeniorPlayerTotalSkillIndex', 5, 0, 'TotalSkillIndex', 'TotalSkillIndexDelta', 1, (SELECT [Id] FROM [app].[Grid] WHERE [GridType] = 0));

-- [app].[GridLayout]
IF NOT EXISTS (SELECT [Id] FROM [app].[GridLayout] WHERE [Name] = 'Default Layout' AND [GridId] = (SELECT [Id] FROM [app].[Grid] WHERE [GridType] = 0))
    INSERT INTO [app].[GridLayout] ([Name], [IsDefault], [GridId]) VALUES ('Default Layout', 1, (SELECT [Id] FROM [app].[Grid] WHERE [GridType] = 0));

-- [app].[GridLayoutColumn]
IF NOT EXISTS (SELECT [Id] FROM [app].[GridLayoutColumn] WHERE [GridColumnId] = (SELECT [Id] FROM [app].[GridColumn] WHERE [Name] = 'ColumnSeniorPlayerHattrickId') AND [GridLayoutId] = (SELECT [Id] FROM [app].[GridLayout] WHERE [IsDefault] = 1 AND [GridId] = (SELECT [Id] FROM [app].[Grid] WHERE [GridType] = 0)))
    INSERT INTO [app].[GridLayoutColumn] ([IsFixed], [Alignment], [DisplayIndex], [DisplayMode], [Width], [GridColumnId], [GridLayoutId]) VALUES (1, 64, 0, 0, 100, (SELECT [Id] FROM [app].[GridColumn] WHERE [Name] = 'ColumnSeniorPlayerHattrickId'), (SELECT [Id] FROM [app].[GridLayout] WHERE [IsDefault] = 1 AND [GridId] = (SELECT [Id] FROM [app].[Grid] WHERE [GridType] = 0)));
IF NOT EXISTS (SELECT [Id] FROM [app].[GridLayoutColumn] WHERE [GridColumnId] = (SELECT [Id] FROM [app].[GridColumn] WHERE [Name] = 'ColumnSeniorPlayerFirstName') AND [GridLayoutId] = (SELECT [Id] FROM [app].[GridLayout] WHERE [IsDefault] = 1 AND [GridId] = (SELECT [Id] FROM [app].[Grid] WHERE [GridType] = 0)))
    INSERT INTO [app].[GridLayoutColumn] ([IsFixed], [Alignment], [DisplayIndex], [DisplayMode], [Width], [GridColumnId], [GridLayoutId]) VALUES (0, 16, 1, 0, 100, (SELECT [Id] FROM [app].[GridColumn] WHERE [Name] = 'ColumnSeniorPlayerFirstName'), (SELECT [Id] FROM [app].[GridLayout] WHERE [IsDefault] = 1 AND [GridId] = (SELECT [Id] FROM [app].[Grid] WHERE [GridType] = 0)));
IF NOT EXISTS (SELECT [Id] FROM [app].[GridLayoutColumn] WHERE [GridColumnId] = (SELECT [Id] FROM [app].[GridColumn] WHERE [Name] = 'ColumnSeniorPlayerNickName') AND [GridLayoutId] = (SELECT [Id] FROM [app].[GridLayout] WHERE [IsDefault] = 1 AND [GridId] = (SELECT [Id] FROM [app].[Grid] WHERE [GridType] = 0)))
    INSERT INTO [app].[GridLayoutColumn] ([IsFixed], [Alignment], [DisplayIndex], [DisplayMode], [Width], [GridColumnId], [GridLayoutId]) VALUES (0, 16, 2, 0, 100, (SELECT [Id] FROM [app].[GridColumn] WHERE [Name] = 'ColumnSeniorPlayerNickName'), (SELECT [Id] FROM [app].[GridLayout] WHERE [IsDefault] = 1 AND [GridId] = (SELECT [Id] FROM [app].[Grid] WHERE [GridType] = 0)));
IF NOT EXISTS (SELECT [Id] FROM [app].[GridLayoutColumn] WHERE [GridColumnId] = (SELECT [Id] FROM [app].[GridColumn] WHERE [Name] = 'ColumnSeniorPlayerLastName') AND [GridLayoutId] = (SELECT [Id] FROM [app].[GridLayout] WHERE [IsDefault] = 1 AND [GridId] = (SELECT [Id] FROM [app].[Grid] WHERE [GridType] = 0)))
    INSERT INTO [app].[GridLayoutColumn] ([IsFixed], [Alignment], [DisplayIndex], [DisplayMode], [Width], [GridColumnId], [GridLayoutId]) VALUES (0, 16, 3, 0, 100, (SELECT [Id] FROM [app].[GridColumn] WHERE [Name] = 'ColumnSeniorPlayerLastName'), (SELECT [Id] FROM [app].[GridLayout] WHERE [IsDefault] = 1 AND [GridId] = (SELECT [Id] FROM [app].[Grid] WHERE [GridType] = 0)));
IF NOT EXISTS (SELECT [Id] FROM [app].[GridLayoutColumn] WHERE [GridColumnId] = (SELECT [Id] FROM [app].[GridColumn] WHERE [Name] = 'ColumnSeniorPlayerAge') AND [GridLayoutId] = (SELECT [Id] FROM [app].[GridLayout] WHERE [IsDefault] = 1 AND [GridId] = (SELECT [Id] FROM [app].[Grid] WHERE [GridType] = 0)))
    INSERT INTO [app].[GridLayoutColumn] ([IsFixed], [Alignment], [DisplayIndex], [DisplayMode], [Width], [GridColumnId], [GridLayoutId]) VALUES (0, 64, 4, 0, 100, (SELECT [Id] FROM [app].[GridColumn] WHERE [Name] = 'ColumnSeniorPlayerAge'), (SELECT [Id] FROM [app].[GridLayout] WHERE [IsDefault] = 1 AND [GridId] = (SELECT [Id] FROM [app].[Grid] WHERE [GridType] = 0)));
IF NOT EXISTS (SELECT [Id] FROM [app].[GridLayoutColumn] WHERE [GridColumnId] = (SELECT [Id] FROM [app].[GridColumn] WHERE [Name] = 'ColumnSeniorPlayerHasHomegrownBonus') AND [GridLayoutId] = (SELECT [Id] FROM [app].[GridLayout] WHERE [IsDefault] = 1 AND [GridId] = (SELECT [Id] FROM [app].[Grid] WHERE [GridType] = 0)))
    INSERT INTO [app].[GridLayoutColumn] ([IsFixed], [Alignment], [DisplayIndex], [DisplayMode], [Width], [GridColumnId], [GridLayoutId]) VALUES (0, 32, 5, 0, 100, (SELECT [Id] FROM [app].[GridColumn] WHERE [Name] = 'ColumnSeniorPlayerHasHomegrownBonus'), (SELECT [Id] FROM [app].[GridLayout] WHERE [IsDefault] = 1 AND [GridId] = (SELECT [Id] FROM [app].[Grid] WHERE [GridType] = 0)));
IF NOT EXISTS (SELECT [Id] FROM [app].[GridLayoutColumn] WHERE [GridColumnId] = (SELECT [Id] FROM [app].[GridColumn] WHERE [Name] = 'ColumnSeniorPlayerAgreeability') AND [GridLayoutId] = (SELECT [Id] FROM [app].[GridLayout] WHERE [IsDefault] = 1 AND [GridId] = (SELECT [Id] FROM [app].[Grid] WHERE [GridType] = 0)))
    INSERT INTO [app].[GridLayoutColumn] ([IsFixed], [Alignment], [DisplayIndex], [DisplayMode], [Width], [GridColumnId], [GridLayoutId]) VALUES (0, 16, 6, 1, 100, (SELECT [Id] FROM [app].[GridColumn] WHERE [Name] = 'ColumnSeniorPlayerAgreeability'), (SELECT [Id] FROM [app].[GridLayout] WHERE [IsDefault] = 1 AND [GridId] = (SELECT [Id] FROM [app].[Grid] WHERE [GridType] = 0)));
IF NOT EXISTS (SELECT [Id] FROM [app].[GridLayoutColumn] WHERE [GridColumnId] = (SELECT [Id] FROM [app].[GridColumn] WHERE [Name] = 'ColumnSeniorPlayerAggressiveness') AND [GridLayoutId] = (SELECT [Id] FROM [app].[GridLayout] WHERE [IsDefault] = 1 AND [GridId] = (SELECT [Id] FROM [app].[Grid] WHERE [GridType] = 0)))
    INSERT INTO [app].[GridLayoutColumn] ([IsFixed], [Alignment], [DisplayIndex], [DisplayMode], [Width], [GridColumnId], [GridLayoutId]) VALUES (0, 16, 7, 1, 100, (SELECT [Id] FROM [app].[GridColumn] WHERE [Name] = 'ColumnSeniorPlayerAggressiveness'), (SELECT [Id] FROM [app].[GridLayout] WHERE [IsDefault] = 1 AND [GridId] = (SELECT [Id] FROM [app].[Grid] WHERE [GridType] = 0)));
IF NOT EXISTS (SELECT [Id] FROM [app].[GridLayoutColumn] WHERE [GridColumnId] = (SELECT [Id] FROM [app].[GridColumn] WHERE [Name] = 'ColumnSeniorPlayerHonesty') AND [GridLayoutId] = (SELECT [Id] FROM [app].[GridLayout] WHERE [IsDefault] = 1 AND [GridId] = (SELECT [Id] FROM [app].[Grid] WHERE [GridType] = 0)))
    INSERT INTO [app].[GridLayoutColumn] ([IsFixed], [Alignment], [DisplayIndex], [DisplayMode], [Width], [GridColumnId], [GridLayoutId]) VALUES (0, 16, 8, 1, 100, (SELECT [Id] FROM [app].[GridColumn] WHERE [Name] = 'ColumnSeniorPlayerHonesty'), (SELECT [Id] FROM [app].[GridLayout] WHERE [IsDefault] = 1 AND [GridId] = (SELECT [Id] FROM [app].[Grid] WHERE [GridType] = 0)));
IF NOT EXISTS (SELECT [Id] FROM [app].[GridLayoutColumn] WHERE [GridColumnId] = (SELECT [Id] FROM [app].[GridColumn] WHERE [Name] = 'ColumnSeniorPlayerLeadership') AND [GridLayoutId] = (SELECT [Id] FROM [app].[GridLayout] WHERE [IsDefault] = 1 AND [GridId] = (SELECT [Id] FROM [app].[Grid] WHERE [GridType] = 0)))
    INSERT INTO [app].[GridLayoutColumn] ([IsFixed], [Alignment], [DisplayIndex], [DisplayMode], [Width], [GridColumnId], [GridLayoutId]) VALUES (0, 16, 9, 2, 100, (SELECT [Id] FROM [app].[GridColumn] WHERE [Name] = 'ColumnSeniorPlayerLeadership'), (SELECT [Id] FROM [app].[GridLayout] WHERE [IsDefault] = 1 AND [GridId] = (SELECT [Id] FROM [app].[Grid] WHERE [GridType] = 0)));
IF NOT EXISTS (SELECT [Id] FROM [app].[GridLayoutColumn] WHERE [GridColumnId] = (SELECT [Id] FROM [app].[GridColumn] WHERE [Name] = 'ColumnSeniorPlayerSpecialty') AND [GridLayoutId] = (SELECT [Id] FROM [app].[GridLayout] WHERE [IsDefault] = 1 AND [GridId] = (SELECT [Id] FROM [app].[Grid] WHERE [GridType] = 0)))
    INSERT INTO [app].[GridLayoutColumn] ([IsFixed], [Alignment], [DisplayIndex], [DisplayMode], [Width], [GridColumnId], [GridLayoutId]) VALUES (0, 16, 10, 0, 100, (SELECT [Id] FROM [app].[GridColumn] WHERE [Name] = 'ColumnSeniorPlayerSpecialty'), (SELECT [Id] FROM [app].[GridLayout] WHERE [IsDefault] = 1 AND [GridId] = (SELECT [Id] FROM [app].[Grid] WHERE [GridType] = 0)));
IF NOT EXISTS (SELECT [Id] FROM [app].[GridLayoutColumn] WHERE [GridColumnId] = (SELECT [Id] FROM [app].[GridColumn] WHERE [Name] = 'ColumnSeniorPlayerWage') AND [GridLayoutId] = (SELECT [Id] FROM [app].[GridLayout] WHERE [IsDefault] = 1 AND [GridId] = (SELECT [Id] FROM [app].[Grid] WHERE [GridType] = 0)))
    INSERT INTO [app].[GridLayoutColumn] ([IsFixed], [Alignment], [DisplayIndex], [DisplayMode], [Width], [GridColumnId], [GridLayoutId]) VALUES (0, 64, 11, 0, 100, (SELECT [Id] FROM [app].[GridColumn] WHERE [Name] = 'ColumnSeniorPlayerWage'), (SELECT [Id] FROM [app].[GridLayout] WHERE [IsDefault] = 1 AND [GridId] = (SELECT [Id] FROM [app].[Grid] WHERE [GridType] = 0)));
IF NOT EXISTS (SELECT [Id] FROM [app].[GridLayoutColumn] WHERE [GridColumnId] = (SELECT [Id] FROM [app].[GridColumn] WHERE [Name] = 'ColumnSeniorPlayerCareerGoals') AND [GridLayoutId] = (SELECT [Id] FROM [app].[GridLayout] WHERE [IsDefault] = 1 AND [GridId] = (SELECT [Id] FROM [app].[Grid] WHERE [GridType] = 0)))
    INSERT INTO [app].[GridLayoutColumn] ([IsFixed], [Alignment], [DisplayIndex], [DisplayMode], [Width], [GridColumnId], [GridLayoutId]) VALUES (0, 64, 12, 0, 100, (SELECT [Id] FROM [app].[GridColumn] WHERE [Name] = 'ColumnSeniorPlayerCareerGoals'), (SELECT [Id] FROM [app].[GridLayout] WHERE [IsDefault] = 1 AND [GridId] = (SELECT [Id] FROM [app].[Grid] WHERE [GridType] = 0)));
IF NOT EXISTS (SELECT [Id] FROM [app].[GridLayoutColumn] WHERE [GridColumnId] = (SELECT [Id] FROM [app].[GridColumn] WHERE [Name] = 'ColumnSeniorPlayerCareerHattricks') AND [GridLayoutId] = (SELECT [Id] FROM [app].[GridLayout] WHERE [IsDefault] = 1 AND [GridId] = (SELECT [Id] FROM [app].[Grid] WHERE [GridType] = 0)))
    INSERT INTO [app].[GridLayoutColumn] ([IsFixed], [Alignment], [DisplayIndex], [DisplayMode], [Width], [GridColumnId], [GridLayoutId]) VALUES (0, 64, 13, 0, 100, (SELECT [Id] FROM [app].[GridColumn] WHERE [Name] = 'ColumnSeniorPlayerCareerHattricks'), (SELECT [Id] FROM [app].[GridLayout] WHERE [IsDefault] = 1 AND [GridId] = (SELECT [Id] FROM [app].[Grid] WHERE [GridType] = 0)));
IF NOT EXISTS (SELECT [Id] FROM [app].[GridLayoutColumn] WHERE [GridColumnId] = (SELECT [Id] FROM [app].[GridColumn] WHERE [Name] = 'ColumnSeniorPlayerBookingStatus') AND [GridLayoutId] = (SELECT [Id] FROM [app].[GridLayout] WHERE [IsDefault] = 1 AND [GridId] = (SELECT [Id] FROM [app].[Grid] WHERE [GridType] = 0)))
    INSERT INTO [app].[GridLayoutColumn] ([IsFixed], [Alignment], [DisplayIndex], [DisplayMode], [Width], [GridColumnId], [GridLayoutId]) VALUES (0, 16, 14, 0, 100, (SELECT [Id] FROM [app].[GridColumn] WHERE [Name] = 'ColumnSeniorPlayerBookingStatus'), (SELECT [Id] FROM [app].[GridLayout] WHERE [IsDefault] = 1 AND [GridId] = (SELECT [Id] FROM [app].[Grid] WHERE [GridType] = 0)));
IF NOT EXISTS (SELECT [Id] FROM [app].[GridLayoutColumn] WHERE [GridColumnId] = (SELECT [Id] FROM [app].[GridColumn] WHERE [Name] = 'ColumnSeniorPlayerInjuryStatus') AND [GridLayoutId] = (SELECT [Id] FROM [app].[GridLayout] WHERE [IsDefault] = 1 AND [GridId] = (SELECT [Id] FROM [app].[Grid] WHERE [GridType] = 0)))
    INSERT INTO [app].[GridLayoutColumn] ([IsFixed], [Alignment], [DisplayIndex], [DisplayMode], [Width], [GridColumnId], [GridLayoutId]) VALUES (0, 64, 15, 0, 100, (SELECT [Id] FROM [app].[GridColumn] WHERE [Name] = 'ColumnSeniorPlayerInjuryStatus'), (SELECT [Id] FROM [app].[GridLayout] WHERE [IsDefault] = 1 AND [GridId] = (SELECT [Id] FROM [app].[Grid] WHERE [GridType] = 0)));
IF NOT EXISTS (SELECT [Id] FROM [app].[GridLayoutColumn] WHERE [GridColumnId] = (SELECT [Id] FROM [app].[GridColumn] WHERE [Name] = 'ColumnSeniorPlayerPlaysOnNationalTeam') AND [GridLayoutId] = (SELECT [Id] FROM [app].[GridLayout] WHERE [IsDefault] = 1 AND [GridId] = (SELECT [Id] FROM [app].[Grid] WHERE [GridType] = 0)))
    INSERT INTO [app].[GridLayoutColumn] ([IsFixed], [Alignment], [DisplayIndex], [DisplayMode], [Width], [GridColumnId], [GridLayoutId]) VALUES (0, 32, 16, 0, 100, (SELECT [Id] FROM [app].[GridColumn] WHERE [Name] = 'ColumnSeniorPlayerPlaysOnNationalTeam'), (SELECT [Id] FROM [app].[GridLayout] WHERE [IsDefault] = 1 AND [GridId] = (SELECT [Id] FROM [app].[Grid] WHERE [GridType] = 0)));
IF NOT EXISTS (SELECT [Id] FROM [app].[GridLayoutColumn] WHERE [GridColumnId] = (SELECT [Id] FROM [app].[GridColumn] WHERE [Name] = 'ColumnSeniorPlayerIsOnTransferMarket') AND [GridLayoutId] = (SELECT [Id] FROM [app].[GridLayout] WHERE [IsDefault] = 1 AND [GridId] = (SELECT [Id] FROM [app].[Grid] WHERE [GridType] = 0)))
    INSERT INTO [app].[GridLayoutColumn] ([IsFixed], [Alignment], [DisplayIndex], [DisplayMode], [Width], [GridColumnId], [GridLayoutId]) VALUES (0, 32, 17, 0, 100, (SELECT [Id] FROM [app].[GridColumn] WHERE [Name] = 'ColumnSeniorPlayerIsOnTransferMarket'), (SELECT [Id] FROM [app].[GridLayout] WHERE [IsDefault] = 1 AND [GridId] = (SELECT [Id] FROM [app].[Grid] WHERE [GridType] = 0)));
IF NOT EXISTS (SELECT [Id] FROM [app].[GridLayoutColumn] WHERE [GridColumnId] = (SELECT [Id] FROM [app].[GridColumn] WHERE [Name] = 'ColumnSeniorPlayerMatchesOnSeniorNationalTeam') AND [GridLayoutId] = (SELECT [Id] FROM [app].[GridLayout] WHERE [IsDefault] = 1 AND [GridId] = (SELECT [Id] FROM [app].[Grid] WHERE [GridType] = 0)))
    INSERT INTO [app].[GridLayoutColumn] ([IsFixed], [Alignment], [DisplayIndex], [DisplayMode], [Width], [GridColumnId], [GridLayoutId]) VALUES (0, 64, 18, 0, 100, (SELECT [Id] FROM [app].[GridColumn] WHERE [Name] = 'ColumnSeniorPlayerMatchesOnSeniorNationalTeam'), (SELECT [Id] FROM [app].[GridLayout] WHERE [IsDefault] = 1 AND [GridId] = (SELECT [Id] FROM [app].[Grid] WHERE [GridType] = 0)));
IF NOT EXISTS (SELECT [Id] FROM [app].[GridLayoutColumn] WHERE [GridColumnId] = (SELECT [Id] FROM [app].[GridColumn] WHERE [Name] = 'ColumnSeniorPlayerMatchesOnJuniorNationalTeam') AND [GridLayoutId] = (SELECT [Id] FROM [app].[GridLayout] WHERE [IsDefault] = 1 AND [GridId] = (SELECT [Id] FROM [app].[Grid] WHERE [GridType] = 0)))
    INSERT INTO [app].[GridLayoutColumn] ([IsFixed], [Alignment], [DisplayIndex], [DisplayMode], [Width], [GridColumnId], [GridLayoutId]) VALUES (0, 64, 19, 0, 100, (SELECT [Id] FROM [app].[GridColumn] WHERE [Name] = 'ColumnSeniorPlayerMatchesOnJuniorNationalTeam'), (SELECT [Id] FROM [app].[GridLayout] WHERE [IsDefault] = 1 AND [GridId] = (SELECT [Id] FROM [app].[Grid] WHERE [GridType] = 0)));
IF NOT EXISTS (SELECT [Id] FROM [app].[GridLayoutColumn] WHERE [GridColumnId] = (SELECT [Id] FROM [app].[GridColumn] WHERE [Name] = 'ColumnSeniorPlayerCategory') AND [GridLayoutId] = (SELECT [Id] FROM [app].[GridLayout] WHERE [IsDefault] = 1 AND [GridId] = (SELECT [Id] FROM [app].[Grid] WHERE [GridType] = 0)))
    INSERT INTO [app].[GridLayoutColumn] ([IsFixed], [Alignment], [DisplayIndex], [DisplayMode], [Width], [GridColumnId], [GridLayoutId]) VALUES (0, 16, 20, 0, 100, (SELECT [Id] FROM [app].[GridColumn] WHERE [Name] = 'ColumnSeniorPlayerCategory'), (SELECT [Id] FROM [app].[GridLayout] WHERE [IsDefault] = 1 AND [GridId] = (SELECT [Id] FROM [app].[Grid] WHERE [GridType] = 0)));
IF NOT EXISTS (SELECT [Id] FROM [app].[GridLayoutColumn] WHERE [GridColumnId] = (SELECT [Id] FROM [app].[GridColumn] WHERE [Name] = 'ColumnSeniorPlayerCountryName') AND [GridLayoutId] = (SELECT [Id] FROM [app].[GridLayout] WHERE [IsDefault] = 1 AND [GridId] = (SELECT [Id] FROM [app].[Grid] WHERE [GridType] = 0)))
    INSERT INTO [app].[GridLayoutColumn] ([IsFixed], [Alignment], [DisplayIndex], [DisplayMode], [Width], [GridColumnId], [GridLayoutId]) VALUES (0, 16, 23, 0, 100, (SELECT [Id] FROM [app].[GridColumn] WHERE [Name] = 'ColumnSeniorPlayerCountryName'), (SELECT [Id] FROM [app].[GridLayout] WHERE [IsDefault] = 1 AND [GridId] = (SELECT [Id] FROM [app].[Grid] WHERE [GridType] = 0)));
IF NOT EXISTS (SELECT [Id] FROM [app].[GridLayoutColumn] WHERE [GridColumnId] = (SELECT [Id] FROM [app].[GridColumn] WHERE [Name] = 'ColumnSeniorPlayerCountryEnglishName') AND [GridLayoutId] = (SELECT [Id] FROM [app].[GridLayout] WHERE [IsDefault] = 1 AND [GridId] = (SELECT [Id] FROM [app].[Grid] WHERE [GridType] = 0)))
    INSERT INTO [app].[GridLayoutColumn] ([IsFixed], [Alignment], [DisplayIndex], [DisplayMode], [Width], [GridColumnId], [GridLayoutId]) VALUES (0, 16, 24, 0, 100, (SELECT [Id] FROM [app].[GridColumn] WHERE [Name] = 'ColumnSeniorPlayerCountryEnglishName'), (SELECT [Id] FROM [app].[GridLayout] WHERE [IsDefault] = 1 AND [GridId] = (SELECT [Id] FROM [app].[Grid] WHERE [GridType] = 0)));
IF NOT EXISTS (SELECT [Id] FROM [app].[GridLayoutColumn] WHERE [GridColumnId] = (SELECT [Id] FROM [app].[GridColumn] WHERE [Name] = 'ColumnSeniorPlayerForm') AND [GridLayoutId] = (SELECT [Id] FROM [app].[GridLayout] WHERE [IsDefault] = 1 AND [GridId] = (SELECT [Id] FROM [app].[Grid] WHERE [GridType] = 0)))
    INSERT INTO [app].[GridLayoutColumn] ([IsFixed], [Alignment], [DisplayIndex], [DisplayMode], [Width], [GridColumnId], [GridLayoutId]) VALUES (0, 16, 25, 2, 100, (SELECT [Id] FROM [app].[GridColumn] WHERE [Name] = 'ColumnSeniorPlayerForm'), (SELECT [Id] FROM [app].[GridLayout] WHERE [IsDefault] = 1 AND [GridId] = (SELECT [Id] FROM [app].[Grid] WHERE [GridType] = 0)));
IF NOT EXISTS (SELECT [Id] FROM [app].[GridLayoutColumn] WHERE [GridColumnId] = (SELECT [Id] FROM [app].[GridColumn] WHERE [Name] = 'ColumnSeniorPlayerStamina') AND [GridLayoutId] = (SELECT [Id] FROM [app].[GridLayout] WHERE [IsDefault] = 1 AND [GridId] = (SELECT [Id] FROM [app].[Grid] WHERE [GridType] = 0)))
    INSERT INTO [app].[GridLayoutColumn] ([IsFixed], [Alignment], [DisplayIndex], [DisplayMode], [Width], [GridColumnId], [GridLayoutId]) VALUES (0, 16, 26, 2, 100, (SELECT [Id] FROM [app].[GridColumn] WHERE [Name] = 'ColumnSeniorPlayerStamina'), (SELECT [Id] FROM [app].[GridLayout] WHERE [IsDefault] = 1 AND [GridId] = (SELECT [Id] FROM [app].[Grid] WHERE [GridType] = 0)));
IF NOT EXISTS (SELECT [Id] FROM [app].[GridLayoutColumn] WHERE [GridColumnId] = (SELECT [Id] FROM [app].[GridColumn] WHERE [Name] = 'ColumnSeniorPlayerKeeper') AND [GridLayoutId] = (SELECT [Id] FROM [app].[GridLayout] WHERE [IsDefault] = 1 AND [GridId] = (SELECT [Id] FROM [app].[Grid] WHERE [GridType] = 0)))
    INSERT INTO [app].[GridLayoutColumn] ([IsFixed], [Alignment], [DisplayIndex], [DisplayMode], [Width], [GridColumnId], [GridLayoutId]) VALUES (0, 16, 27, 2, 100, (SELECT [Id] FROM [app].[GridColumn] WHERE [Name] = 'ColumnSeniorPlayerKeeper'), (SELECT [Id] FROM [app].[GridLayout] WHERE [IsDefault] = 1 AND [GridId] = (SELECT [Id] FROM [app].[Grid] WHERE [GridType] = 0)));
IF NOT EXISTS (SELECT [Id] FROM [app].[GridLayoutColumn] WHERE [GridColumnId] = (SELECT [Id] FROM [app].[GridColumn] WHERE [Name] = 'ColumnSeniorPlayerDefending') AND [GridLayoutId] = (SELECT [Id] FROM [app].[GridLayout] WHERE [IsDefault] = 1 AND [GridId] = (SELECT [Id] FROM [app].[Grid] WHERE [GridType] = 0)))
    INSERT INTO [app].[GridLayoutColumn] ([IsFixed], [Alignment], [DisplayIndex], [DisplayMode], [Width], [GridColumnId], [GridLayoutId]) VALUES (0, 16, 28, 2, 100, (SELECT [Id] FROM [app].[GridColumn] WHERE [Name] = 'ColumnSeniorPlayerDefending'), (SELECT [Id] FROM [app].[GridLayout] WHERE [IsDefault] = 1 AND [GridId] = (SELECT [Id] FROM [app].[Grid] WHERE [GridType] = 0)));
IF NOT EXISTS (SELECT [Id] FROM [app].[GridLayoutColumn] WHERE [GridColumnId] = (SELECT [Id] FROM [app].[GridColumn] WHERE [Name] = 'ColumnSeniorPlayerPlaymaking') AND [GridLayoutId] = (SELECT [Id] FROM [app].[GridLayout] WHERE [IsDefault] = 1 AND [GridId] = (SELECT [Id] FROM [app].[Grid] WHERE [GridType] = 0)))
    INSERT INTO [app].[GridLayoutColumn] ([IsFixed], [Alignment], [DisplayIndex], [DisplayMode], [Width], [GridColumnId], [GridLayoutId]) VALUES (0, 16, 29, 2, 100, (SELECT [Id] FROM [app].[GridColumn] WHERE [Name] = 'ColumnSeniorPlayerPlaymaking'), (SELECT [Id] FROM [app].[GridLayout] WHERE [IsDefault] = 1 AND [GridId] = (SELECT [Id] FROM [app].[Grid] WHERE [GridType] = 0)));
IF NOT EXISTS (SELECT [Id] FROM [app].[GridLayoutColumn] WHERE [GridColumnId] = (SELECT [Id] FROM [app].[GridColumn] WHERE [Name] = 'ColumnSeniorPlayerWinger') AND [GridLayoutId] = (SELECT [Id] FROM [app].[GridLayout] WHERE [IsDefault] = 1 AND [GridId] = (SELECT [Id] FROM [app].[Grid] WHERE [GridType] = 0)))
    INSERT INTO [app].[GridLayoutColumn] ([IsFixed], [Alignment], [DisplayIndex], [DisplayMode], [Width], [GridColumnId], [GridLayoutId]) VALUES (0, 16, 30, 2, 100, (SELECT [Id] FROM [app].[GridColumn] WHERE [Name] = 'ColumnSeniorPlayerWinger'), (SELECT [Id] FROM [app].[GridLayout] WHERE [IsDefault] = 1 AND [GridId] = (SELECT [Id] FROM [app].[Grid] WHERE [GridType] = 0)));
IF NOT EXISTS (SELECT [Id] FROM [app].[GridLayoutColumn] WHERE [GridColumnId] = (SELECT [Id] FROM [app].[GridColumn] WHERE [Name] = 'ColumnSeniorPlayerPassing') AND [GridLayoutId] = (SELECT [Id] FROM [app].[GridLayout] WHERE [IsDefault] = 1 AND [GridId] = (SELECT [Id] FROM [app].[Grid] WHERE [GridType] = 0)))
    INSERT INTO [app].[GridLayoutColumn] ([IsFixed], [Alignment], [DisplayIndex], [DisplayMode], [Width], [GridColumnId], [GridLayoutId]) VALUES (0, 16, 31, 2, 100, (SELECT [Id] FROM [app].[GridColumn] WHERE [Name] = 'ColumnSeniorPlayerPassing'), (SELECT [Id] FROM [app].[GridLayout] WHERE [IsDefault] = 1 AND [GridId] = (SELECT [Id] FROM [app].[Grid] WHERE [GridType] = 0)));
IF NOT EXISTS (SELECT [Id] FROM [app].[GridLayoutColumn] WHERE [GridColumnId] = (SELECT [Id] FROM [app].[GridColumn] WHERE [Name] = 'ColumnSeniorPlayerScoring') AND [GridLayoutId] = (SELECT [Id] FROM [app].[GridLayout] WHERE [IsDefault] = 1 AND [GridId] = (SELECT [Id] FROM [app].[Grid] WHERE [GridType] = 0)))
    INSERT INTO [app].[GridLayoutColumn] ([IsFixed], [Alignment], [DisplayIndex], [DisplayMode], [Width], [GridColumnId], [GridLayoutId]) VALUES (0, 16, 32, 2, 100, (SELECT [Id] FROM [app].[GridColumn] WHERE [Name] = 'ColumnSeniorPlayerScoring'), (SELECT [Id] FROM [app].[GridLayout] WHERE [IsDefault] = 1 AND [GridId] = (SELECT [Id] FROM [app].[Grid] WHERE [GridType] = 0)));
IF NOT EXISTS (SELECT [Id] FROM [app].[GridLayoutColumn] WHERE [GridColumnId] = (SELECT [Id] FROM [app].[GridColumn] WHERE [Name] = 'ColumnSeniorPlayerSetPieces') AND [GridLayoutId] = (SELECT [Id] FROM [app].[GridLayout] WHERE [IsDefault] = 1 AND [GridId] = (SELECT [Id] FROM [app].[Grid] WHERE [GridType] = 0)))
    INSERT INTO [app].[GridLayoutColumn] ([IsFixed], [Alignment], [DisplayIndex], [DisplayMode], [Width], [GridColumnId], [GridLayoutId]) VALUES (0, 16, 33, 2, 100, (SELECT [Id] FROM [app].[GridColumn] WHERE [Name] = 'ColumnSeniorPlayerSetPieces'), (SELECT [Id] FROM [app].[GridLayout] WHERE [IsDefault] = 1 AND [GridId] = (SELECT [Id] FROM [app].[Grid] WHERE [GridType] = 0)));
IF NOT EXISTS (SELECT [Id] FROM [app].[GridLayoutColumn] WHERE [GridColumnId] = (SELECT [Id] FROM [app].[GridColumn] WHERE [Name] = 'ColumnSeniorPlayerLoyalty') AND [GridLayoutId] = (SELECT [Id] FROM [app].[GridLayout] WHERE [IsDefault] = 1 AND [GridId] = (SELECT [Id] FROM [app].[Grid] WHERE [GridType] = 0)))
    INSERT INTO [app].[GridLayoutColumn] ([IsFixed], [Alignment], [DisplayIndex], [DisplayMode], [Width], [GridColumnId], [GridLayoutId]) VALUES (0, 16, 34, 2, 100, (SELECT [Id] FROM [app].[GridColumn] WHERE [Name] = 'ColumnSeniorPlayerLoyalty'), (SELECT [Id] FROM [app].[GridLayout] WHERE [IsDefault] = 1 AND [GridId] = (SELECT [Id] FROM [app].[Grid] WHERE [GridType] = 0)));
IF NOT EXISTS (SELECT [Id] FROM [app].[GridLayoutColumn] WHERE [GridColumnId] = (SELECT [Id] FROM [app].[GridColumn] WHERE [Name] = 'ColumnSeniorPlayerExperience') AND [GridLayoutId] = (SELECT [Id] FROM [app].[GridLayout] WHERE [IsDefault] = 1 AND [GridId] = (SELECT [Id] FROM [app].[Grid] WHERE [GridType] = 0)))
    INSERT INTO [app].[GridLayoutColumn] ([IsFixed], [Alignment], [DisplayIndex], [DisplayMode], [Width], [GridColumnId], [GridLayoutId]) VALUES (0, 16, 35, 2, 100, (SELECT [Id] FROM [app].[GridColumn] WHERE [Name] = 'ColumnSeniorPlayerExperience'), (SELECT [Id] FROM [app].[GridLayout] WHERE [IsDefault] = 1 AND [GridId] = (SELECT [Id] FROM [app].[Grid] WHERE [GridType] = 0)));
IF NOT EXISTS (SELECT [Id] FROM [app].[GridLayoutColumn] WHERE [GridColumnId] = (SELECT [Id] FROM [app].[GridColumn] WHERE [Name] = 'ColumnSeniorPlayerTotalSkillIndex') AND [GridLayoutId] = (SELECT [Id] FROM [app].[GridLayout] WHERE [IsDefault] = 1 AND [GridId] = (SELECT [Id] FROM [app].[Grid] WHERE [GridType] = 0)))
    INSERT INTO [app].[GridLayoutColumn] ([IsFixed], [Alignment], [DisplayIndex], [DisplayMode], [Width], [GridColumnId], [GridLayoutId]) VALUES (0, 64, 36, 0, 100, (SELECT [Id] FROM [app].[GridColumn] WHERE [Name] = 'ColumnSeniorPlayerTotalSkillIndex'), (SELECT [Id] FROM [app].[GridLayout] WHERE [IsDefault] = 1 AND [GridId] = (SELECT [Id] FROM [app].[Grid] WHERE [GridType] = 0)));